### ISSUE TITLE
Message signing

### ISSUE THREAD

**Issue by FeatureSpitter** [LedgerHQ/ledger-live#1014]
Please implement message signing with a bitcoin address in the new app. This feature was available in the old chrome app.

Thanks!

OP: https://github.com/LedgerHQ/ledger-live-desktop/issues/1136

**Comment by gre** [comment]
Hi and sorry for the delay in answering on this Github issue.
We now only use Github issues for developers topics (typically on topics that concerns our SDK, libraries,..). For questions, feature requests or Ledger Live issues, please go through our Customer Support to raise this voice and have it more prioritised: https://support.ledger.com/

Thanks

**Comment by tzarebczan** [comment]
@gre is there another issue open for this feature anywhere to track it? BIP322 is getting more usage now to validate ordinals ownership, other wallets are adding it also. 

Please have your team take a look :)

**Comment by FlorianWendelborn** [comment]
> Hi and sorry for the delay in answering on this Github issue.

Are you implying you even answered this?

IS THIS HELLO-WORLD-LEVEL BASIC FEATURE STILL NOT SUPPORTED AFTER 11 YEARS?

What a joke of a hardware wallet Ledgers are.
