### ISSUE TITLE
deeplinks with tokens

### ISSUE THREAD

**Issue by oritwoen** [LedgerHQ/ledger-live#1035]
**Context**

Deeplinks are quite a nice feature but from what I noticed they don't support tokens.

There is no mention of it in the documentation and I have tried in various ways and nothing works.

**Is your feature request related to a problem? Please describe.**

Deeplinks do not support tokens. It is problematic for companies that would like to automate the process of refilling hot-wallets automatically using the button so as not to make a mistake when entering data.

**Describe the solution you'd like**

new `token` query:

`ledgerlive://send?currency=eth&token=usdc`

**Describe alternatives you've considered**

Unfortunately, I did not find any alternative.

**Comment by mateitudose** [comment]
I believe that they also don't work when trying to set a recipient address, which is quite frustrating.

**Comment by oritwoen** [comment]
I'll see how difficult it is. If I can handle the code, I can add PR.

**Comment by gre** [comment]
Hi and sorry for the delay in answering on this Github issue.
We now only use Github issues for developers topics (typically on topics that concerns our SDK, libraries,..). For questions, feature requests or Ledger Live issues, please go through our Customer Support to raise this voice and have it more prioritised: https://support.ledger.com/

Thanks
