### ISSUE TITLE
How to list erc20 token in app

### ISSUE THREAD

**Issue by bobimicroweber** [LedgerHQ/ledger-live#1294]
Hello team, can you tell me how can i add erc20 token in UI list ? Token is based on a polygon matic network

**Comment by leoDEVa** [comment]
@bobimicroweber Please see the link below to our dedicated support line:

Support :[Polygon Live Support](docs-pollygonnetwork.com)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by haammar-ledger** [comment]
Hi @bobimicroweber please refer to our documentation on the subject: https://developers.ledger.com/docs/token/introduction/
Thanks.
