### ISSUE TITLE
[Bug]: Error when building from release archive without git repo

### ISSUE THREAD

**Issue by phnx47** [LedgerHQ/ledger-live#1719]
### Impacted Library name

@ledgerhq/live-desktop

### Describe the bug

Original issue: https://github.com/LedgerHQ/ledger-live-desktop/issues/3918

For ArchLinux AUR [ledger-live](https://aur.archlinux.org/packages/ledger-live) we download archive from tag:
![image](https://user-images.githubusercontent.com/1101691/198834069-7304af63-e652-4847-af99-32ff3cfbccb3.png)

It cannot be build without `.git` folder. You have direct `git` call from your code:
https://github.com/LedgerHQ/ledger-live/blob/bf9e7a242c349d565a0fdcd6823059295920fb58/apps/ledger-live-desktop/tools/utils/index.js#L14-L17

Can you not call `git` during build?

### Expected behavior

No implicit build dependency on git repository. Removed `git` call.

**Comment by valpinkman** [comment]
Not critical for now but will take a look whenever I can

**Comment by phnx47** [comment]
bump to keep this ticket open

**Comment by valpinkman** [comment]
@phnx47 we will take a look at it when we get some bandwidth ;)

**Comment by phnx47** [comment]
I suggest this solution

```js
let GIT_REVISION = process.env?.GIT_REVISION;

if (!GIT_REVISION) {
  GIT_REVISION = childProcess
    .execSync("git rev-parse --short HEAD")
    .toString("utf8")
    .trim();
}
```
When I will build code without `.git` folder I can set `GIT_REVISION` by env. I can raise PR for this fix and test it.

**Comment by valpinkman** [comment]
Sorry for the delay, your code seems more than alright, implementing it in a PR right now

**Comment by valpinkman** [comment]
@phnx47 I'm testing that it doesn't break our build system, and if it's good, it will be merged to develop and be shipped with the next LLD release ;)

**Comment by phnx47** [comment]
@valpinkman Thanks!
