### ISSUE TITLE
[Question]: aTokens displayed use internal API or directly call AAVE contract(s) (LendingPool)?

### ISSUE THREAD

**Issue by GittyGitGitGitty** [LedgerHQ/ledger-live#1744]
### Library name

@ledgerhq/live-desktop@2.49.2

### Describe your feature request

Hi Ledger,

I see that aTokens are now showing an accurate balance over time, with interest accruing. As far as I can tell, this is a somewhat new feature but I don't know when or where it was introduced.

Could you please help me find where this happens? I don't know if you are calling a contract directly or using an (internal) Ledger API within your servers.

Thank you.

**Comment by gre** [comment]
Hello, i'm very sorry for the delay but Ledger Live Desktop is not a library, for questions it is better to directly contact our customer support, Github issues is currently mainly be used for tracking discussion around technical libraries.

https://support.ledger.com/

**Comment by GittyGitGitGitty** [comment]
Hi @gre . So what I get from this answer is that the implementation is within a library somewhere, but you don't indicate which library. Is it an upstream library? All I'm asking is how the *app* gets the appropriate information. Thank you.
