### ISSUE TITLE
[Bug]: Ledger Live on Windows 10 Loses Accounts

### ISSUE THREAD

**Issue by sipsorcery** [LedgerHQ/ledger-live#1787]
### Describe the bug

The Ledger Live Desktop app on Windows 10 regularly loses all my Bitcoin accounts forcing a 30-40 minute resync. This behaviour started 3-4 months ago.

### Expected behavior

Accounts don't get lost.

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledger.com/  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://live.ledger.tools/logsviewer )

**Comment by sipsorcery** [comment]
I tried the support avenue before logging this issue. It's very difficult to even create an issue with Ledger support and even when I did so there was a pre-canned response with a no-reply address.
