### ISSUE TITLE
[Bug]: Ledger Live doesn't respect region settings

### ISSUE THREAD

**Issue by jernejp21** [LedgerHQ/ledger-live#1788]
### Describe the bug

Ledger Live (version 2.49.2) on Windows 10 doesn't respect region settings. It's always in weird format. MM/DD/YYYY and AM/PM. I would like the app to respect region format.

### Expected behavior

Clock and date format should update with different region selected.

### Additional context

Choosing region and restarting the app doesn't change date and time format.

In app.json file: `"region":null,"locale":"sl-SI"`. Region is null, while locale is set correctly.

**Comment by Dricc123** [comment]
Not fixed. Please reopen this ticket.

**Comment by jernejp21** [comment]
This issue still hasn't been fixed. It always uses American format, regardless of locale.

**Comment by jernejp21** [comment]
When is develop version going into production? I have version 2.69.0 on Linux and it still doesn't work.

Date should be 15. 10. 2023. And time should be 24 hour format.

![ZajemzaslonaDeepin_izberi-območje_20231101073509](https://github.com/LedgerHQ/ledger-live/assets/61543115/faef7e77-f481-4d37-8327-8760cb5b7c42)


Under "Latest operations" date format is correct, but time format is not.
