### ISSUE TITLE
[Feature]: Add currency `sats`

### ISSUE THREAD

**Issue by mothepro** [LedgerHQ/ledger-live#1804]
### Library name

ledger-live-desktop

### Describe your feature request

Having `BTC` as a currency option is great. ie `0.354 BTC`
But showing `sats` is a cleaner approach making it easier to see your total at a glance. ie `35,400,000 sats`

**Comment by gre** [comment]
Hi @mothepro, this feature is already available in the Account settings.

<img width="962" alt="Screenshot 2022-11-22 at 19 03 55" src="https://user-images.githubusercontent.com/211411/203388435-15193d32-5b40-4001-96dc-80215ac4245c.png">
<img width="930" alt="Screenshot 2022-11-22 at 19 03 27" src="https://user-images.githubusercontent.com/211411/203388442-766c428d-bd7d-40c6-8888-c1f60177b16a.png">
