### ISSUE TITLE
[Feature]: Add bluetooth support to ledger live desktop

### ISSUE THREAD

**Issue by stevenknieven** [LedgerHQ/ledger-live#1992]
### Describe your feature request

Hello, please add bluetooth support to ledger live desktop, would be very helpfull and much appreciated.
thanks

**Comment by elbywan** [comment]
Hey @stevenknieven,

We do not accept feature requests regarding our Ledger Live apps on Github. With that said, adding bluetooth on desktop is definitely on our roadmap.

**Comment by stevenknieven** [comment]
@elbywan i see, it's good to know it's on the roadmap, thanks for your response.
