### ISSUE TITLE
[Bug]: Ledger SDK Sign Message

### ISSUE THREAD

**Issue by gobeli** [LedgerHQ/ledger-live#2077]
### Impacted Library name

@ledgerhq/live-app-sdk

### Impacted Library version

0.8.2

### Describe the bug

I would like to sign an arbitrary message from a "Ledger Live Non-Dapp". 
The process seems to work and the message signing popup is successfully showing up and I can sign the message, as soon as the process is done though I get the following Error over jsonrpc: 
```
{
    "jsonrpc": "2.0",
    "id": 2,
    "error": {
        "code": 0,
        "message": "An object could not be cloned."
    }
}
```
I am calling the sign-message function like so:
```js
// accountId = valid accountId retreived from the LedgerLivePlatformSDK
// messageToSign = arbitrary string
api.signMessage(accountId, Buffer.from(messageToSign));
```

What am I missing?

### Expected behavior

I would expect, that the message signing is successful and returned in the promise resolution of the `signMessage` return promise.

**Comment by elbywan** [comment]
Hey @gobeli,

This library is not part of this monorepository and is hosted in its own repository: https://github.com/LedgerHQ/live-app-sdk

Could you please post the issue there?
Thanks
