### ISSUE TITLE
[Feature]: Starred Accounts on the left bar is partially visible

### ISSUE THREAD

**Issue by tntc4** [LedgerHQ/ledger-live#2107]
### Describe your feature request

I have 3 Starred Accounts and they are shown on the left part of the Ledger Live App.
Only first two are completely visible and the last one is partially visible, but there are more space that is not used to show them all.
Can we use that space to show all starred accounts?
See screenshot I have attached.
![Screenshot_1](https://user-images.githubusercontent.com/3246834/206879702-f3e40b78-7cd6-450b-9ad7-0a8de068de4f.jpg)

**Comment by elbywan** [comment]
Hey @tntc4,

> Regarding Ledger Applications (Ledger Live Desktop, Ledger Live Mobile) we are only accepting bugfixes for the moment. There is a good chance that we will reject feature based PRs based on the fact that they do not fit our roadmap or our long-term goals.

_https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#disclaimer_

For questions, feature requests or Ledger Live issues, please go through our Customer Support at https://support.ledger.com/

**Comment by bruno-t-de-renzo** [comment]
In fact I believe it's a bug, because in the past this box was not horizontally limited and would adapt to bigger screens. I would suggest to look into this issue as a bug. Thanks

**Comment by tatijana** [comment]
ok thanks :)

Den ons 15 mars 2023 kl 15:24 skrev bruno-t-de-renzo <
***@***.***>:
