### ISSUE TITLE
[Bug]: Sign Qtum transaction failed with Ledger

### ISSUE THREAD

**Issue by EV6999** [LedgerHQ/ledger-live#2164]
### Impacted Library name

@ledgerhq/hw-app-btc

### Impacted Library version

8.1.0

### Describe the bug

The following error happens when trying to sign Qtum transaction failed with Ledger.

Error message:
`'Something went wrong during signing: data.length exceed 256 bytes limit. Got: 271'`

The error only happens when UTXO that was generated from Offline Staking smart contract is specified as input of the transaction.

Example UTXOs:
- https://qtum.info/tx/3188b3302216d3c4bbb133df72dadddbd00854b590161383495386a05dbadecc
- https://qtum.info/tx/72b7f31dc9b4acc06b57575ab9b9ed12887f62602a8eee9fc18d88dba746f95a

### Expected behavior

The sign of Qtum transaction with Ledger should work no matter how the UTXO was generated.

**Comment by puruoni** [comment]
Same. Because of this validation, I cannot use UTXO generated by a delegate transaction
https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledgerjs/packages/hw-transport/src/Transport.ts#L204
