### ISSUE TITLE
[Bug]: Unable to resolve "@ledgerhq/devices/ble/sendAPDU" - react-native-hw-transport-ble @ 6.27.11

### ISSUE THREAD

**Issue by KillianH** [LedgerHQ/ledger-live#2185]
### Impacted Library name

@ledgerhq/react-native-hw-transport-ble

### Impacted Library version

6.27.11

### Describe the bug

Upgrading the lib from 6.27.10 to 6.27.11+ I got the error : 

Unable to resolve "@ledgerhq/devices/ble/sendAPDU" from "node_modules/@ledgerhq/react-native-hw-transport-ble/lib/BleTransport.js"

I checked the PR merged in 6.27.11 and couldn't find anything related to that.

Using : 

    "react-native": "0.70.5",
    "expo": "^47.0.0",
    "react": "18.1.0",

### Expected behavior

The lib should resolve the sendAPDU method.

**Comment by hankminden** [comment]
I am experiencing this error as well

**Comment by hankminden** [comment]
Ended up having to downgrade these packages to resolve this error:

    "@ledgerhq/hw-app-eth": "6.29.9",
    "@ledgerhq/react-native-hw-transport-ble": "6.27.10",

**Comment by elbywan** [comment]
This is regression, should will be fixed when #2304 lands 🤞.

**Comment by KillianH** [comment]
> This is regression, should will be fixed when #2304 lands 🤞.

Thanks !
