### ISSUE TITLE
[Bug]: Task :ledgerhq_react-native-hid:verifyReleaseResources failed

### ISSUE THREAD

**Issue by sonytooo** [LedgerHQ/ledger-live#2274]
### Impacted Library name

@ledgerhq/react-native-hid

### Describe the bug

After updating to Expo SDK 47 bare and applying these steps in the android folder: [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.69.6&to=0.70.5) from the Expo migration guide, the production build and ./gradlew assembleRelease (APK generation) fail with error: 

`> Task :ledgerhq_react-native-hid:verifyReleaseResources FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

* What went wrong:
Execution failed for task ':ledgerhq_react-native-hid:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Applications/Ambire/ambire-mobile-wallet/node_modules/@ledgerhq/react-native-hid/android/build/intermediates/merged_res/release/values/values.xml:2722: AAPT: error: resource android:attr/lStar not found.
` 

### Expected behavior

Expo SDK 45 included react-native: 0.68.2 and there was no issue building on Android with this package

**Comment by humarkx** [comment]
Any news on this issue?

**Comment by humarkx** [comment]
For anyone else facing the same problem, I have created this `patch` which allows the `@ledgerhq/react-native-hid` package to be compiled with the latest sdk version 33

```diff --git a/node_modules/@ledgerhq/react-native-hid/android/build.gradle b/node_modules/@ledgerhq/react-native-hid/android/build.gradle
index d6eebd0..7fd0018 100644
--- a/node_modules/@ledgerhq/react-native-hid/android/build.gradle
+++ b/node_modules/@ledgerhq/react-native-hid/android/build.gradle
@@ -6,7 +6,7 @@ buildscript {
   }
 
   dependencies {
-    classpath 'com.android.tools.build:gradle:3.5.1'
+    classpath("com.android.tools.build:gradle:7.3.1")
   }
 }
 
@@ -21,11 +21,10 @@ allprojects {
 apply plugin: 'com.android.library'
 
 android {
-  compileSdkVersion 29
-
+  compileSdkVersion 33
   defaultConfig {
     minSdkVersion 24
-    targetSdkVersion 29
+    targetSdkVersion 33
     versionCode 1
     versionName "1.0"
   }```
