### ISSUE TITLE
[Feature]: Support SPL tokens on Ledger Live

### ISSUE THREAD

**Issue by ilyazub** [LedgerHQ/ledger-live#2302]
### Library name

`@ledgerhq/app-solana`

### Describe your feature request

How to track SPL tokens in Ledger Live? If it's not supported yet, what are the high-level steps to implement? (I'm happy to submit a PR to [`LedgerHQ/app-solana`](https://github.com/LedgerHQ/app-solana) if needed.)

Please let me know what your team's thoughts are. Thanks!

---

_Previous feature request in a deprecated `ledger-live-desktop` repository: https://github.com/LedgerHQ/ledger-live-desktop/discussions/4005_.

**Comment by ilyazub** [comment]
@LedgerHQ What your team thinks about the support of SPL tokens on Ledger Live?

**Comment by selat** [comment]
I found a commit from Dec 2021 where support for SPL tokens was disabled: https://github.com/LedgerHQ/ledger-live/commit/70fa34ee2470eb0035c075cc58ce01291dcfde7f

@LedgerHQ would it be possible to enable it back?

**Comment by haammar-ledger** [comment]
Hi @ilyazub @selat, unfortunately support of SPL tokens in Ledger Live is not on the roadmap at the moment.
