### ISSUE TITLE
[Feature]: releasing apk for direct download

### ISSUE THREAD

**Issue by 3point14159** [LedgerHQ/ledger-live#2438]
### Describe your feature request

Most wallets allow you to download and authenticate apk downloads outside of Google Play. This is important for the growing number of users that use apps outside of the Google ecosystem. Google should not be considered a good actor" after they revoked their "Don't be evil" motto. That should be a huge red flag for anyone paying attention. This should be relatively simple to do anyway, so I ask in closing; why not?

**Comment by coolRoger** [comment]
I need apk source download too

**Comment by coolRoger** [comment]
@ledgerlive

**Comment by meriadec** [comment]
Whole app is open source, so I guess an even better workaround is to directly build the app from source, which give you opportunity to review the code for extra safety!
