### ISSUE TITLE
[Bug]: Ledger HID does not work on Android 12+

### ISSUE THREAD

**Issue by tzechuen** [LedgerHQ/ledger-live#2525]
### Impacted Library name

@ledgerhq/react-native-hid

### Impacted Library version

6.28.12

### Describe the bug

When trying to connect to the Ledger device using `TransportHID.open(device)` on an Android 12 device, an error is thrown:

```
[Error: com.myapp.wallet: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.]
```

### Expected behavior

It should not throw the error and Ledger connection via HID using an Android 12 device should be successful

### Additional context

I suspect this pull request could've fixed it, but it went stale:

https://github.com/LedgerHQ/ledger-live/pull/1771

**Comment by juan-cortes** [comment]
Hey @tzechuen thanks for reporting this, I missed both this issue and the proposed pull request 🤦🏼‍♂️.
However!, **[we've tackled this in our current sprint](https://github.com/LedgerHQ/ledger-live/pull/2718)** and it's currently being validated and reviewed. Feel free to **[test the build](https://github.com/LedgerHQ/ledger-live/actions/runs/4245674379)** if you want and see if it detects your device again, I'll close the issue now but if you find issues on the build please report them on the PR.
