### ISSUE TITLE
[Bug]: doesn't redirect back to app after sending transaction using walletconnect on flutter

### ISSUE THREAD

**Issue by AmjadKhan2k18** [LedgerHQ/ledger-live#2615]
### Describe the bug

I am working on a flutter Application in which we are using Ledger through WalletConnect

for deep link I am using ```ledgerlive://```

I connected Application and send transaction but when user is connected or confirm sending a transaction user stay on Ledger Live app and doesn't redirect back to our app same as Other wallet Metamask/TrustWallet

is there any Universal link for Ledger live app available ? 

Apple recommend to use universal link instead of deeplink but I didn't find any in documentation 
there was another issue on old repository
https://github.com/LedgerHQ/ledger-live-mobile/issues/2425

### Expected behavior

user should be redirected back when connect or send transaction successfully

**Comment by Chukwulawrence** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by CustomerTeam001** [comment]
@AmjadKhan2k18 We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8
