### ISSUE TITLE
[Bug]: `AURORA` token name has a minor typo

### ISSUE THREAD

**Issue by 0x3bfc** [LedgerHQ/ledger-live#2802]
### Impacted Library name

@ledgerhq/cryptoassets

### Impacted Library version

8.0.0

### Describe the bug

The `AURORA` token has a minor typo in the name (`an extra space` in `Aurora( NEAR)`. I tried to update it in that [PR](https://github.com/LedgerHQ/ledger-live/pull/2544) but it seems that there is an extra step needed to make the PR valid based on the automatic checks.

### Expected behavior

The token name should be `Aurora(NEAR)`

**Comment by 0x3bfc** [comment]
@gre any help with this ?

**Comment by juan-cortes** [comment]
Hello @0x3bfc, sadly this fix needs to be done at a private repository that serves as the data source for the list you tried to edit on ledger-live. I've created an internal bug and assigned someone to it so it will be addressed, thank you for taking the time to attempt a fix.
