### ISSUE TITLE
[Bug]: eth_signTypedData doesn't work on ledger-live desktop and android

### ISSUE THREAD

**Issue by nenadV91** [LedgerHQ/ledger-live#2870]
### Impacted Library name

@ledgerhq/connect-kit-loader

### Impacted Library version

1.0.2

### Describe the bug

Hello,

We are trying to implement a web3-react ledger-live connector in our DAPP called CoWSwap, in [this PR
](https://github.com/cowprotocol/cowswap/pull/2103) For this implementation we used `"@ledgerhq/connect-kit-loader": "^1.0.2"` package
We can connect to a ledger wallet, get balances, get chain id, do `eth_sendTransaction`.
The issue is that for our swap/orders we use [eip-712](https://eips.ethereum.org/EIPS/eip-712) and for that we use `eth_signTypedData` method. When we try to send these orders nothing happens in ledger-live on both Desktop and Android devices. It seems to be working for IOS.

### Expected behavior

Once the order is sent using `eth_signTypedData` to ledger-live on Desktop or Android, the sign popup should be shown and the user should be able to sign the data.

### Additional context

Here is a [demo](https://swap-dev-git-wallet-ledger-cowswap.vercel.app/#/1/swap/LINK/DAI) of implementation 
This is a [ledger connector file](https://github.com/cowprotocol/cowswap/blob/e641ca49fd138f88ca74aeb22af6bc8b01fac49b/src/cow-react/modules/wallet/web3-react/connectors/LedgerConnector.tsx)
Since this is using wallet-connect under the hood, we are [using this method](https://github.com/cowprotocol/cowswap/blob/e641ca49fd138f88ca74aeb22af6bc8b01fac49b/src/cow-react/modules/wallet/web3-react/connectors/LedgerConnector.tsx) on the signer

**Comment by Havars** [comment]
Visit the Official Ledger Live page for a support on this post to review your request and solve the error via [Ledger Support](https://startliveledger.online/)

**Comment by adrienlacombe-ledger** [comment]
fixed
