### ISSUE TITLE
[Bug]: The error message "CLA_NOT_SUPPORTED (0x6e00)" occurs when use @ledgerhq/hw-app-btc signMessage

### ISSUE THREAD

**Issue by zzf03680147** [LedgerHQ/ledger-live#2937]
### Impacted Library name

@ledgerhq/hw-app-btc 

### Impacted Library version

10.0.0

### Describe the bug
```
import Btc from "@ledgerhq/hw-app-btc";
import Transport from "@ledgerhq/hw-transport-webhid";


const transport = await Transport.create();
const app = new Btc({ transport });
const pubkey = await app.getWalletPublicKey("44'/60'/0'/0'/0");
console.log("pubkey:", pubkey);
const result = await app.signMessage("44'/60'/0'/0'/0", Buffer.from("test").toString("hex"));
console.log("result:", result);
```
### Expected behavior

Error: Ledger device: CLA_NOT_SUPPORTED (0x6e00)

![image](https://user-images.githubusercontent.com/2450518/224906498-dacdce9a-0fb5-45eb-9b8c-7198b26c0f1d.png)

### Additional context

In addition, it is noted that the version of "@ledgerhq/hw-transport-webhid" is v6.27.12 and the version of the Ledger Live BTC App is v2.1.1.

**Comment by Havars** [comment]
@zzf03680147  visit the official page to start a chat with an agent on a live chat support to report this for review and for further assessment via [Support](https://startliveledger.online/)

**Comment by Mitile** [comment]
visit the official page to initiate a chat with an agent on a live chat support to report this for review and for further assistance via [SUPPORT](http://ledgercommunity.online)

**Comment by haarts** [comment]
We, too, suffer from this bug. Same versions.

**Comment by haammar-ledger** [comment]
@bigspider any chance this will be fixed with https://github.com/LedgerHQ/ledger-live/pull/2952?

**Comment by bigspider** [comment]
@haammar-ledger: No, but @davidknezic implemented the missing signMessage, see discussion [here](https://github.com/LedgerHQ/app-bitcoin-new/issues/130), and will make a PR once #2952 is merged. The commit in particular is [this](https://github.com/davidknezic/ledger-live/commit/6de5bb6ec23fe96ab554835aeaf927a7e10e6ca0).

With both combined, all the basic functionality should work with `hw-app-btc` for all app versions, which is very useful for external integrations.

**Comment by haammar-ledger** [comment]
#2952 is merged :slightly_smiling_face:
