### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'call') On Production (NUXT 3)

### ISSUE THREAD

**Issue by SurhanZahid** [LedgerHQ/ledger-live#2973]
### Impacted Library name

@ledgerhq/hw-app-btc

### Impacted Library version

10.0.0

### Describe the bug

On production this function
`const { bitcoinAddress } = await appBtc.getWalletPublicKey("44'/0'/0'/0/0");`
throws this an error.
Cannot read properties of undefined (reading 'call')
This error only appears on production locally it works fine. I am using NUXT 3 on production the commands I am using are.
`yarn generate`
`yarn preview`

### Expected behavior

This function should just return the public BTC key from the ledger hardware device and not throw an error

**Comment by gvash** [comment]
Getting the same issue @SurhanZahid @noirbizarre. Is there any workaround?

**Comment by iamonuwa** [comment]
this issue still exists, is there a fix for this please?
