### ISSUE TITLE
[Bug]: can't connect via bluetooth since change the device name

### ISSUE THREAD

**Issue by akinazuki** [LedgerHQ/ledger-live#2987]
### Describe the bug

I changed the device name to `Nazuki's Cold Wallet` in Ledger Live iOS app, but since I changed the name, I can no longer connect via Bluetooth.
I'm sure the Bluetooth of Ledger is enabled

![2478DEED-8182-458C-8EC4-81989CA738ED_1_102_a](https://user-images.githubusercontent.com/43605695/226123652-eb265d54-19c4-43b6-84f4-2acc5fb86126.jpeg)
![AEAD62D0-E7B1-4E1C-A191-94F6E7B05504_1_102_o](https://user-images.githubusercontent.com/43605695/226123674-c955e40a-5ad3-4638-986b-66dfce38b5ad.jpeg)

the USB connection is normal

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/43605695/226123806-b1d5f475-ba5a-48f2-af10-b2f89ee01267.png">

Model: Ledger Nano X
Ledger Live App Version: 3.16.1 (4)
Secure Element Version: 2.1.0
Microcontroller Version: 2.30
Bootloader 1.16

### Expected behavior

I'm not sure this issue can be reproduce, my friend change the name too, but they can use the bluetooth normally
I haven't try to reset the device

**Comment by Mitile** [comment]
visit the official page to initiate a chat with an agent on a live chat support to report this for review and for further assistance via [SUPPORT](http://ledgercommunity.online)

**Comment by Krys0me** [comment]
-On your phone, forget your Ledger device in Bluetooth settings.
-On Ledger, hold both buttons to access the General settings>Settings>Security>Reset Pairings>[scroll past "Cancel" to confirm "! Reset Pairings">Insert Pass-code
-Reconnect using the Ledger Live app. 
qualifications: I had the same problem

**Comment by juan-cortes** [comment]
Interesting, I'm taking a look to see if it can qualify as a bug on our side. Changing the name should have no impact over the visibility of the device when trying to scan for it. We've recently introduced some improvements to the Ble transport but it will take some time for them to land on the production version. Until then, the workaround suggested by @Krys0me should work, as unfortunate as it may be.

**Comment by juan-cortes** [comment]
I found time to look into the issue and there really seems to be something going on, in fact, a reproducible scenario at least for LNX 2.1.0 is naming the device 20 Ws, after doing so the BLE stack seems to break. I've forwarded the topic to our firmware team and I'll update this when it's solved with the conclusions.
