### ISSUE TITLE
[Feature]: Add a search textbox on top of the "discover"

### ISSUE THREAD

**Issue by abarbier13127** [LedgerHQ/ledger-live#3000]
### Describe your feature request

Hello,

In the Discover Panel, it could be fine to have a search textbox on top to be able to find quickly the app we want to use.

Small feature but helping us to be more efficient when we want to use an app in the Ledger Live

CU

Alf

**Comment by adrienlacombe-ledger** [comment]
soon on mobile and next is desktop :)
