### ISSUE TITLE
[Bug]: Intermittent error "Permission denied by user for device" thrown by TransportHID.open()

### ISSUE THREAD

**Issue by tzechuen** [LedgerHQ/ledger-live#3018]
### Impacted Library name

@ledgerhq/react-native-hid

### Impacted Library version

6.29.0

### Describe the bug

When calling `TransportHID.open()` to connect to Ledger, it usually throws this error `[DisconnectedDevice: Permission denied by user for device]` on the first attempt. However, weirdly it was able to connect on the 2nd try

### Expected behavior

It should be able to connect without intermittent errors

### Additional context

This was tested on an Android 12 device with a Ledger Nano X

**Comment by Mitile** [comment]
visit the official page to initiate a chat with an agent on a live chat support to report this for review and for further assistance via [SUPPORT](http://ledgercommunity.online)

**Comment by GHOLLAM** [comment]
Visit the official page to initiate a chat with an agent on the live chat to report this for review and for further assistance via [Ledger chat](http://Helpdeskledgerr.online)

**Comment by juan-cortes** [comment]
This error is coming **[from the native part of the transport](https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledgerjs/packages/react-native-hid/android/src/main/java/com/ledgerwallet/hid/ReactHIDModule.java#L209)**, in particular the `UsbManager.EXTRA_PERMISSION_GRANTED` check. This code is ancient, but it would seem to point to attempting to connect before the permission checks are resolved? Something curious is that we do have a `retry` twice in our setup, so perhaps it's an expected failure the first connection attempt 😕 

https://github.com/LedgerHQ/ledger-live/blob/197d28697b173c3f6b2badfe4d1deddeadc912d4/apps/ledger-live-mobile/src/live-common-setup.ts#L105-L107

Tracking it internally as https://ledgerhq.atlassian.net/browse/LIVE-6996

I'll update this issue when we have time to tackle it.

**Comment by tzechuen** [comment]
Hey guys, any updates on this issue?
