### ISSUE TITLE
[Feature]: update behavior when search returns nothing

### ISSUE THREAD

**Issue by adrienlacombe-ledger** [LedgerHQ/ledger-live#3025]
### Describe your feature request

- update "no app found" to "not found"
- if the element that is being searched is a url, update "please retry the search with another keyword." by "please retry the search with another keyword or open **this_url** in a browser" and this_url would be a deeplink to actually open the url in the default browser

**Comment by JunichiSugiura** [comment]
> open this_url in a browser

@adrienlacombe-ledger Does it indicates this screen is not a browser? 🤨

**Comment by adrienlacombe-ledger** [comment]
> > open this_url in a browser
> 
> @adrienlacombe-ledger Does it indicate this screen is not a browser? raised_eyebrow

good catch ... let's change then to "open this_url outside Ledger Live"

**Comment by JunichiSugiura** [comment]
Oops, I merged too early.

**Comment by adrienlacombe-ledger** [comment]
> Oops, I merged too early. I'll prepare another PR to change.

haha yeah, let's update that ;)
