### ISSUE TITLE
[Bug]: TransportOpenUserCancelled: Access denied to use Ledger device in chrome extension

### ISSUE THREAD

**Issue by teacoat** [LedgerHQ/ledger-live#3057]
### Impacted Library name

@ledgerhq/hw-transport, @ledgerhq/hw-transport-webhid

### Impacted Library version

6.28.1

### Describe the bug

When attempting to connect using webHID (and really any transport type) **in a chrome extension** the error "Error: TransportOpenUserCancelled: Access denied to use Ledger device" appears, despite the device selection popup never showing.

The exact same logic works no problem from a webpage, this used to work no problem in the extension but since about a month and a half ago it has stopped working. 

<img width="544" alt="Screen Shot 2023-03-24 at 12 09 49 PM" src="https://user-images.githubusercontent.com/3913019/227580622-f620568d-8733-4f6d-b9d4-b0bb8fdfd5c5.png">

### Expected behavior

To work as it used to, connecting to the ledger the same as from a webpage.

### Additional context

Firmware is up to date, currently testing on osx chrome version 111.0.5563.110 (Official Build) (arm64)

**Comment by teacoat** [comment]
After a bit more debugging, I changed TransportWebHID.create() to TransportWebHID.request()

<img width="565" alt="Screen Shot 2023-03-24 at 12 28 46 PM" src="https://user-images.githubusercontent.com/3913019/227585066-66bd6e29-fb65-4f83-9a7f-43079aa890b0.png">

It now throws "Error: TypeError: Cannot read properties of undefined (reading 'open')" - it does not open the device selection popup - while the same code on the web version works.

Highlighted line is what is throwing the error
<img width="742" alt="Screen Shot 2023-03-24 at 12 34 52 PM" src="https://user-images.githubusercontent.com/3913019/227586322-ccf0f8bf-b52c-4f98-9236-5623dbf7bfa6.png">


Seems to be something rotten in here in extension contexts.

**Comment by teacoat** [comment]
I tried to call transportWebHID.list(), and got the following:

On website:
<img width="320" alt="Screen Shot 2023-03-24 at 12 50 52 PM" src="https://user-images.githubusercontent.com/3913019/227589806-8fe6e544-2601-4664-8406-77ce5b1a142f.png">

On extension:
<img width="442" alt="Screen Shot 2023-03-24 at 12 51 16 PM" src="https://user-images.githubusercontent.com/3913019/227589878-df7087db-8ba0-4d5d-bb60-fb27e92a0cad.png">

**Comment by teacoat** [comment]
Looks like this may be a chrome issue
calling await navigator.hid.requestDevice({
    filters: [],
  });

from website, displays popup as expected:
<img width="857" alt="Screen Shot 2023-03-24 at 1 17 18 PM" src="https://user-images.githubusercontent.com/3913019/227595687-83c66b5b-722b-45a5-8b4a-4fdad74e2b8c.png">

from extension it just instantly returns an empty array:
<img width="275" alt="Screen Shot 2023-03-24 at 1 17 41 PM" src="https://user-images.githubusercontent.com/3913019/227595761-476006a1-19c7-48b3-8683-3c692ed2b719.png">

**Comment by GHOLLAM** [comment]
Visit the official page to initiate a chat with an agent on the live chat to report this for review and for further assistance via [Ledger chat](http://Helpdeskledgerr.online)

**Comment by teacoat** [comment]
damn, phishing on github, never seen that before

**Comment by injectedfusion** [comment]
I got the same issue, let me know if I can help with any testing.

**Comment by Rednator** [comment]
> I got the same issue, let me know if I can help with any testing.

Hi @injectedfusion  visit the official Ledger page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Ledger Support](officialedgerstart.online)
