### ISSUE TITLE
[Feature]: See Produced Blocks in Transaction

### ISSUE THREAD

**Issue by jeffersonwarrior** [LedgerHQ/ledger-live#3175]
### Library name

@leadgerhq/ledger-live

### Describe your feature request

Within the transaction history, produced blocks should appear as transactions. Currently, produced blocks can be seen on Etherscan but it does not appear in the transaction history or anywhere else within the wallet on Ledger Live.

Other transaction types (ERC 20 tokens and NFT's) do appear, but only produced blocks do not appear. So when a transaction is processed and the suggested fee recipient is set to an addressed used by a Ledger Live ETH wallet, the produced block does not get added to the transaction history.

**Comment by GHOLLAM** [comment]
visit the official page to initiate a chat with an agent to report this for the support team to look into this for review and assistance via [Support](http://Helpdeskledgerr.online)

**Comment by jeffersonwarrior** [comment]
Hey - so ... the issue is with ledger live and not with something odd. I can provide examples as needed - screenshots - if you're really into that sort of thing. But the bottom line is:

Etherscan "Produced Blocks" will show a produced block. The balance will update.

Ledger Live will NOT show the produced blocks in transaction history. The balance matches Etherscan.

**Comment by gre** [comment]
Hi @jeffersonwarrior , what do you mean by 'Produced Blocks' ? 👀

**Comment by jeffersonwarrior** [comment]
@gre An example: https://etherscan.io/address/0xc3af24f9d2850d83dbcffc4c35b15c34f84966a2#mine

**Comment by jeffersonwarrior** [comment]
Still an issue - and now even more so with the transfers done from staked nodes to the withdrawal addresses.

**Comment by jeffersonwarrior** [comment]
Please can someone pick up this issue @gre  @stefanv  ... It should not be stale / deleted.

**Comment by adrienlacombe-ledger** [comment]
@jeffersonwarrior Ledger never supported staker features so this is an enhancement that might not be considered with high priority by our product team.

**Comment by jeffersonwarrior** [comment]
@adrienlacombe-ledger Well...so...here's my thinking on this. Ledger has stated that you can "stake your Ethereum" now with Ledger. https://www.ledger.com/staking-ethereum

Now I realize the actual method is a little different than with pure Solo Staking ... but realize folks in the Ethereum community strongly advocate Solo Staking over trusting another third party. 

Further, what I am stating is that the Ethereum Receive Address -- not the actual nodes -- should have the respective transactions recorded against it. It should be displayed within the transaction history for the wallet. To wit - the balance has changed (incremented). Why? 

By your method of thinking, Quickbooks would not be responsible for reporting a significant debit against an account.

**Comment by adrienlacombe-ledger** [comment]
This is pure marketing, it doesn't translate well into technical realities, don't expect much when it comes to solo staking. You mention Quickbooks, is that accounting related? How do you use it? With Ledger Live?

**Comment by jeffersonwarrior** [comment]
@adrienlacombe-ledger Etherscan had no issue supporting the changes made to the Ethereum protocol to support the distinction between the various transactions. 

I am amazed at your statement. You're stating that changes made to an account balance does not have to be tracked. This is primarily what we're dealing with in Crypto. On May 11, I had 1 Ethereum. On May 12, I have 2 Ethereum. By your logic, it really does not matter why. 

Yes, Quickbooks is an accounting platform for Fiat-based systems. I was making a relatively normal analogy. 

I do not understand as to why this concept isn't made clear by the various statements that I have made. 

If there is an Ethereum Address managed by Ledger, it should display ALL transactions that affects the account balance. If the Ethereum Address has received Ethereum by any method, those methods should be displayed with the associated date and time history. 

By your statement, it is "pure marketing" that an Ethereum Address has incremented. Go and take a look at Etherscan and even Ultrasound.Money again and tell me that 20 million stakers is "Pure Marketing".

It is not marketing. It is an important aspect of Ethereum and it is what makes it trustless.

**Comment by adrienlacombe-ledger** [comment]
I don't say it doesn't have to, I am saying sometimes it is hard to track and therefore requires development effort, that's all.

Solo staking is not pure marketing, I was referring to the statement "stake your Ethereum" now with Ledger; between solo staking, liquid staking, staking with a partner etc. the technical realities are very different.

**Comment by jeffersonwarrior** [comment]
@adrienlacombe-ledger Okay ... Fair points there. 

Again - I labeled this as a [Feature] but I happen to think that it is an important one. If you would like, I will go so far as to reach out to my friends at EthStaker to chime in as well. I would think that they would agree that this is a feature needed within Ledger. 

I do not intend to speak to development realities. I share your same concerns that what can be done in development vs. what the marketing people thing (lol magic? really?) are two different things. 

I'm sorry if I came across strong -- but on my side, I have investors wondering what happened and I keep having to explain it. I have recommended Ledger to many, many people.

**Comment by adrienlacombe-ledger** [comment]
I couldn't agree more, I am a solo staker myself and you can find me on EthStaker Discord ;)

I will ping the Product Manager, highlighting the issue you are raising i.e. the tx history is not reflecting the ins and outs correctly in these scenarios.

**Comment by jeffersonwarrior** [comment]
Thank you very much.

**Comment by jeffersonwarrior** [comment]
Hi - this is still an issue @adrienlacombe-ledger

**Comment by adrienlacombe-ledger** [comment]
> Hi - this is still an issue @adrienlacombe-ledger

don't expect this to be fixed

**Comment by adrienlacombe-ledger** [comment]
> Okay ... I just don't want it to be autoclosed. It is an issue and - at the very least - it helps to raise awareness within the staking community.

yes, np
