### ISSUE TITLE
[Feature]: add new account when the last created account of that crypto asset has not received a transaction yet

### ISSUE THREAD

**Issue by fredlacs** [LedgerHQ/ledger-live#3220]
### Library name

@ledgerhq/ledger-live-desktop

### Describe your feature request

It is not possible to add a new account to a particular cryptoasset when the last createdaccount has not received a transaction yet.

This creates friction when a user wants to create multiple accounts to be signers in multisigs.
Typically in multisigs multiple holders don't need to hold any assets since they just sign messages offchain, then a single executor needs funds to actually execute it.

Allowing to add new accounts without requiring funds on the previously created account will greatly reduce friction when using Ledger Live alongside multisigs.

**Comment by klinki** [comment]
That would be great, I also miss this feature. I was playing with metamask and it allows to create new account without having funds on the previous one. Now I have account which is impossible to add to Ledger Live :(

**Comment by gre** [comment]
i believe this is a product choice and we strictly apply the BIP44 standard on this https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#user-content-Account

> Software should prevent a creation of an account if a previous account does not have a transaction history (meaning none of its addresses have been used before).

for this reason, I'm not aware a product change on this matter will happen any time soon, it would only make the discovery of account (in finite time) more hard for the whole ecosystem if we start allowing account to exist in any N>1 future empty account.

Indeed, Ethereum has been an exception where it has been possible in other wallet to discover such account and we have put in place some logic that will go up to N+10 when we scan for non empty accounts, but it will only find non empty account, it will not encourage the creation of more non empty than 1 at a time (in the current implementation).

Hope this explanation is clear 🙏 

Best,
gre

**Comment by klinki** [comment]
I understand automatic account discovery would be hard and the reasoning why not to do it. But it would be great if there was some advanced mode where user would have more control and he could for example manually set the account number.
