### ISSUE TITLE
[Feature]: Request to Add TON Support to Ledger Live

### ISSUE THREAD

**Issue by besoeasy** [LedgerHQ/ledger-live#3318]
### Describe your feature request

Hello Ledger Live Team,

I am a TON (The Open Network) user and I would like to request that TON support be added to Ledger Live. I noticed that your website currently lists TON as a supported asset on Ledger devices, but Ledger Live does not currently support TON.

I understand that the TON team has already developed a solution for Ledger hardware wallets, which can be found at https://github.com/ton-blockchain/ledger-app-ton-old. It would be great if you could add TON support to Ledger Live soon, so that TON users can easily manage their assets using the Ledger Live software.

As a long-time user of Ledger products, I appreciate the effort that your team puts into supporting various cryptocurrencies and ensuring the security of users' assets. Adding support for TON would be a great step towards expanding the range of supported assets and improving the overall user experience.

Thank you for your consideration, and I look forward to hearing from you soon.

Best regards

**Comment by besoeasy** [comment]
Website : https://ton.org/

**Comment by besoeasy** [comment]
Anything ?

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
