### ISSUE TITLE
[Feature]: Support custom tokens

### ISSUE THREAD

**Issue by MathiasGilson** [LedgerHQ/ledger-live#3327]
### For Ledger Live Desktop

[ledger-live-desktop](https://github.com/LedgerHQ/ledger-live/tree/develop/apps/ledger-live-desktop)

### Describe your feature request

# Support custom tokens

For example, Rocket Pool ETH is not yet supported on Ledger Live Desktop.

It would be great to be able to have a way to import tokens like in Metamask

<img width="357" alt="Screenshot 2023-04-29 at 00 03 02" src="https://user-images.githubusercontent.com/7348817/235267459-8c3c799c-73ee-4fd6-ad7f-39b59e5f2e11.png">

I can try to make a PR if this is request is popular

Many thanks!

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. Unfortunately, we are not directly managing Ledger Live's feature requests on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
