### ISSUE TITLE
[Bug]: coin-framework is not built before being published to NPMJS

### ISSUE THREAD

**Issue by emmanuelm41** [LedgerHQ/ledger-live#3330]
### Impacted Library name

@ledgerhq/coin-framework

### Impacted Library version

0.3.1

### Describe the bug

This is the content on the package on the NPMJS registry

![image](https://user-images.githubusercontent.com/10941036/235452537-1a188623-0ae0-4936-9cd5-916eb2eb4066.png)

And this is the exports field on the package.json

```
"exports": {
    "./lib/*": "./lib/*.js",
    "./lib/*.js": "./lib/*.js",
    "./lib-es/*": "./lib-es/*.js",
    "./lib-es/*.js": "./lib-es/*.js",
    "./*": {
      "require": "./lib/*.js",
      "default": "./lib-es/*.js"
    },
    "./*.js": {
      "require": "./lib/*.js",
      "default": "./lib-es/*.js"
    },
```

As you can see here, in order this package to work, lib and lib-es folder should be there. Those folders are generated when running the build process (tsc). That should happen before publishing the package. 

This bug was found when trying to use getDeviceInfo function from @ledgerhq/live-common. This is the error I saw. 
![image](https://user-images.githubusercontent.com/10941036/235452902-b5ea7fcf-d5ba-4211-b8b5-88417927c927.png)

If I run `npm run build` on the local copy I have on my project (inside node_modules), the lib and lib-es folders are generated and the error is gone.

### Expected behavior

The package should have lib and lib-es folders there in order for them to work.

**Comment by haammar-ledger** [comment]
@emmanuelm41 Issue solved, available on develop. :slightly_smiling_face:
