### ISSUE TITLE
[Bug]: Can't connect to Bitcoin Core RPC with default empty credentials 

### ISSUE THREAD

**Issue by keith-gardner** [LedgerHQ/ledger-live#3373]
### Impacted Library name

ledger-live

### Describe the bug

Default Bitcoin Core bitcoin.conf file contains only one line and wallets like https://github.com/sparrowwallet/sparrow
use empty credentials by default to connect to it: 
<img width="530" alt="Screen Shot 2023-05-05 at 8 33 43 PM" src="https://user-images.githubusercontent.com/74844722/236588648-2951d6dd-5eb1-44a7-9b0c-95e74595de6e.png">

### Expected behavior

Request: To allow empty credential to be entered in order to connect to core.
<img width="494" alt="Screen Shot 2023-05-05 at 8 33 53 PM" src="https://user-images.githubusercontent.com/74844722/236588670-59032f7c-b09f-4658-a04c-9cdbb7d01b46.png">

### Additional context

CC https://github.com/LedgerHQ/ledger-live-desktop/issues/4173

**Comment by adrienlacombe-ledger** [comment]
@keith-gardner this is just to generate the satstack config file. Have you tried launching satstack without cred? Does it work?
