### ISSUE TITLE
[Bug]: Electron Forge apps fail to `make` / `start` with latest `@ledgerhq/hw-transport-node-hid` version

### ISSUE THREAD

**Issue by rossbulat** [LedgerHQ/ledger-live#3416]
### Impacted Library name

@ledgerhq/hw-transport-node-hid

### Impacted Library version

6.27.14

### Describe the bug

macOS version: 13.3.1 (a).

The `usb` package fails to build. Here is the output when running `yarn make`. The same occurs when trying to start the project:

```
      ✖ [plugin-webpack] Preparing native dependencies: 1 / 2
        › node-gyp failed to rebuild '/Users/macbookpro/polkadot/project/node_modules/usb'
      ◼ [plugin-webpack] Building webpack bundles
```

Followed by:
```
An unhandled rejection has occurred inside Forge:
Error: node-gyp failed to rebuild '/Users/macbookpro/polkadot/project/node_modules/usb'
at ChildProcess.<anonymous> (/Users/macbookpro/polkadot/project/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:118:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

### Expected behavior

Making and starting successfully.

### Additional context

`@ledgerhq/hw-transport-node-hid` depends on `usb` version `1.9.1`. This is the version that is breaking.

If I just install the latest `usb` version `2.9.0` as a dependency (and remove `@ledgerhq/hw-transport-node-hid `) and run `yarn make` and `yarn start`, the app works fine. 

Perhaps updating `usb` to version 2 will fix this.

**Comment by rossbulat** [comment]
Has anyone been able to review this?

**Comment by gre** [comment]
#3625 was merged and this should now be fixed. thanks for your patience
