### ISSUE TITLE
[Bug]: Centrifuge app Incorrect visualization on Ledger X / Crashing

### ISSUE THREAD

**Issue by ImdioR** [LedgerHQ/ledger-live#3449]
### Describe the bug

1. Centrifuge App 1.0.0.7
Incorrect visualization on Ledger X
![image](https://github.com/LedgerHQ/ledger-live/assets/90972248/c240b670-f326-4b96-8c6f-e7cc43065506)
![image](https://github.com/LedgerHQ/ledger-live/assets/90972248/3577da62-cde9-409c-8d48-4e286d0681b4)

2. Also the application is crushing after 10-15s.
Can you please take a look? 

### Expected behavior

1. Correct visualization
2. Correct working

**Comment by ImdioR** [comment]
Anyone?

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

Unfortunately this doesn't relates to this repository, we prefer to investigate such issues via contacting our customer support team.

could you please contact our support team and mention this github issue? https://support.ledger.com/  🙏

**Comment by ImdioR** [comment]
HI
Unfortunately, they also work in the same way.
Ledger Support - Case 1073525
40+ days without a reply.

Looks like they also closed the ticket without even replying  

"Great work"!!! (NOPE)

Will share this conversation on tweeter!
