### ISSUE TITLE
[Bug]: Coin selection / Batching.  Wallet replaced and merged a previous transaction without adjusting the new total.

### ISSUE THREAD

**Issue by nostitos** [LedgerHQ/ledger-live#3504]
### Impacted Library version

LEDGER LIVE OSX

### Describe the bug

While I understand this could be a fee saving technique to batch unfirmed, The accounting is wrong AND not much was saved since an extra input was needlessly selected.

![image](https://github.com/LedgerHQ/ledger-live/assets/48504624/70f72619-a06f-4e50-84ed-28fc7c578e24)

Final transaction : https://mempool.space/tx/1858f2bca7d94b5d7f4596fb1c1aa60770a82554c81a1e6fd17fee1ac4678a5a

The 0.001 BTC was replaced but the new transaction didn't include that 0.001 

### Expected behavior

Two transactions,

Or a replacement that sums up to both.

**Comment by nostitos** [comment]
additionally Ledger Live keep the transaction in the history once the replacement is confirmed, even after refreshing the wallet.

Here is what wasting time on shitcoin integration leads you to.

Fail at basic Bitcoin support.

**Comment by adrie0** [comment]
Hi @nostitos visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ledger Support](https://connectlegders.online/)

**Comment by hzheng-ledger** [comment]
@nostitos 
maybe you can try the "clear cache" button(top right corner settings -> Help -> clear cache)
it would recalculate the transactions and fix the balance. Thanks.

**Comment by nostitos** [comment]
The damage is done, Had to fight with the person who claimed he sent two transaction.

**Ledger Live crafted a RBF transaction that include the inputs of another previous unconfirmed transaction. Cancelling the first one via double spend in the process.**

Do you see the inputs of that one?
https://mempool.space/tx/1858f2bca7d94b5d7f4596fb1c1aa60770a82554c81a1e6fd17fee1ac4678a5a

Ledger Live is such a broken and bloated piece of shitcoin trash.

**Comment by hzheng-ledger** [comment]
@nostitos I guess that the person who claimed that he sent two transactions doesn't use Ledger-live to do the transactions.
All the transactions sent by Ledger-live is non-Rbf transactions with today's implementation

**Comment by nostitos** [comment]
> 1. he sent two transactions doesn't use Ledger-live to do the transactions.

It was done by a noob users using Ledger X on ipad.

The only issue was that the customer thought he sent two Tx instead of one. And that's what ledger live was showing even a day later.
