### ISSUE TITLE
[Feature]: Add EURC token support for Avalanche c chain

### ISSUE THREAD

**Issue by saadjhk** [LedgerHQ/ledger-live#3571]
### Library name

ledgerjs

### Describe your feature request

Avalanche c chain accounts should be able to list ERC20 based token EURC. I have gone through the files in `libs\ledgerjs\packages\cryptoassets` and it seems like c chain ERC20 assets are not added at all.

**Comment by adrie0** [comment]
Hi @saadjhk visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ledger Support](https://connectlegders.online/)

**Comment by adrienlacombe-ledger** [comment]
the previous message is a scam

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. Unfortunately, we are not directly managing Ledger Live's feature requests on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
