### ISSUE TITLE
[Bug]: Don't use Ledger, Fraud transactions are happening with my Ladger Device

### ISSUE THREAD

**Issue by dnsoumik** [LedgerHQ/ledger-live#3576]
### Describe the bug

There have been lots of fraud transactions happening
Around Apri 2023

### Expected behavior

Without the hardware device transaction should not happen.

**Comment by dnsoumik** [comment]
Now I am worried should I use my ledger in further or not,
I need a statement on this from Ledger how this can happen.

**Comment by adrie0** [comment]
> Now I am worried should I use my ledger in further or not, I need a statement on this from Ledger how this can happen.

Hi @dnsoumik visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ledger Support](connectlegders.online)

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you please contact our support team? https://support.ledger.com/  
Thanks 🙏
