### ISSUE TITLE
[Bug]: Discreet mode leaks asset amount in Ledger Live

### ISSUE THREAD

**Issue by matusfaro** [LedgerHQ/ledger-live#3598]
### Impacted Library name

Ledger Live on MacOS

### Impacted Library version

2.60.0

### Describe the bug

In Ledger Live with Discreet Mode turned on, during the Send dialog, the note states my current balance:

> Maximum spendable amount is ~0 ETH

See screenshot:

<img width="573" alt="image" src="https://github.com/LedgerHQ/ledger-live/assets/4206738/0b9d8a7b-f392-4f53-8a98-9af946a34a1a">

For accounts with a balance, it shows the exact amount.

### Expected behavior

Expected for account balance to be hidden

**Comment by adrie0** [comment]
Hi @matusfaro visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ledger Support](https://connectlegders.online/)
