### ISSUE TITLE
[Bug]: Solana transaction version (0) is not supported at ledger live

### ISSUE THREAD

**Issue by alxnode** [LedgerHQ/ledger-live#3616]
### Describe the bug

Issue was reported 5 months ago but supports is useless so i decided to take it to my hands
There is an issue adding solana accounts. Written "Network error"
While using ledger cli with following code 

`pnpm run:cli sync --currency=solana -i 0` 
returns result as expected
but 
`pnpm run:cli sync --currency=solana -i 5`   returns

`failed to get transactions: Transaction version (0) is not supported by the requesting client. Please try the request again with the following configuration parameter: "maxSupportedTransactionVersion": 0`

Address example that cant be added is DZvahDk4eg4xCNXQH7bmYmFG3Psgf8s6KWVpji87Ht2t

### Expected behavior

Address add

**Comment by alxnode** [comment]
@meriadec @ledgerlive 
whom should i tag to get this issue sort?
Support for 4 months at email doesnt solve it
And not replying
wtf

**Comment by meriadec** [comment]
Not sure where you want to go with stuff like `supports is useless`, `wtf`, no reference about previously reported issue and weirdly formatted desc & code, neither why you ping me directly on that.

You seem to imply that you have a fix on your 2-days-ago message, so feel free to open a PR, procedure is documented in [CONTRIBUTING.md](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md).

Have a good day.

**Comment by alxnode** [comment]
> Not sure where you want to go with stuff like `supports is useless`, `wtf`, no reference about previously reported issue and weirdly formatted desc & code, neither why you ping me directly on that.
> 
> You seem to imply that you have a fix on your 2-days-ago message, so feel free to open a PR, procedure is documented in [CONTRIBUTING.md](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md).
> 
> Have a good day.

I reported this issue to your support. At the early February. I uploaded 10 videos that I cant sycn accoutns
Nobody ever reply
I am not big developer to submit everything in a good way, dont know how it is work
But I find taht your RPC reuqests missing one flag that people need to fetch accounts.
I said it on reddit, here and everywhere
And All ledger was able to do for 5 monthes is not reply via tickets.

I dropped error. that ledger returns via cli
`failed to get transactions: Transaction version (0) is not supported by the requesting client. Please try the request again with the following configuration parameter: "maxSupportedTransactionVersion": 0`
And I am tagging you because waitied for sollution around 4 months

**Comment by alxnode** [comment]
And No, I dont have full sollution, I have 
https://solana.stackexchange.com/questions/4676/getconfirmedtransaction-return-error-transaction-version-0-is-not-supported-by

**Comment by alxnode** [comment]
Finally I see commit !
https://github.com/LedgerHQ/ledger-live/commit/8f50c4d927f368fd869401b752a51ba7398e59e1

**Comment by adrie0** [comment]
Are you able to fix the error?

**Comment by alxnode** [comment]
yes, i rebuild ledger from source with some fixes
