### ISSUE TITLE
ARM build for Apple Silicon Macs

### ISSUE THREAD

**Issue by muuvmuuv** [LedgerHQ/ledger-live#363]
**Describe the bug**

The x64 build via Rosetta 2 hangs a lot during exchange. An ARM build would be much better and give improved security because of no transformation through Rosetta.

**To Reproduce**

**Expected behavior**

_A clear and concise description of what you expected to happen._

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Desktop (please complete the following information):**
 - OS: any macOS with Silicon

**Smartphone (please complete the following information):**

**Additional context**

_Add any other context about the problem here._

**Comment by valpinkman** [comment]
Already being worked on ;) 
https://github.com/LedgerHQ/ledger-live/pull/253
It should come out in the next release, or n+1 if we have issues on QA
