### ISSUE TITLE
[Bug]: new AppBtc(transport) failing 

### ISSUE THREAD

**Issue by dhruvtyagi** [LedgerHQ/ledger-live#3689]
### Impacted Library name

@ledgerhq/hw-app-btc
@ledgerhq/react-native-hid 

### Impacted Library version

10.0.4

### Describe the bug

import TransportHID from "@ledgerhq/react-native-hid";
import AppBtc from "@ledgerhq/hw-app-btc";

TransportHID.create().then (
   async transport => {
      const btc = new AppBtc(transport);
   }
);

The third line in this bug is throwing the following error:

TypeError: Cannot read property 'decorateAppAPIMethods' of undefined 

### Expected behavior

It should not throw the error

### Additional context

I'm trying to build the react-native-hid sample app for Android. I was able to do so for Ethereum but I'm unable to do the same for Bitcoin.

**Comment by eniewold** [comment]
I was getting the same error when updating my libraries to the latest version. I've double checked and a remake of the sample code at [Web USB/HID Javascript Integration Walkthrough](https://developers.ledger.com/docs/transport/web-hid-usb/) will result in the mentioned error. I will postpone updating my libraries until there is news on how to resolve this...

**Comment by dhruvtyagi** [comment]
Can you mention the version you are currently using? The one that is working.

**Comment by eniewold** [comment]
I've done some digging, and it seems the problem occurs since the **@ledgerhq/hw-app-btc version 9.1.0 release**. If you import the 9.0.1 version the error no longer occurs and communcation can be established. I've not validated the communication itself, just the technical interface and the ledger responding.

**Comment by adrienlacombe-ledger** [comment]
@haammar-ledger do you know maybe?
