### ISSUE TITLE
[Bug]: Can't use signMessage() after updated the firmware to 2.1.0 in VUE

### ISSUE THREAD

**Issue by SanIP117** [LedgerHQ/ledger-live#3799]
### Impacted Library name

@ledgerhq/hw-app-btc

### Impacted Library version

10.0.3 - 10.0.5

### Describe the bug

I can't use the `signMessage()` after my ledger nano x & nano s upgraded the firmware to 2.1.0 in my vue project
it keep return `"list" argument must be an Array of Buffers`, tried on `10.0.3`, `10.0.4`, `10.0.5`
it only happen on vue environment, use parcel + core-js is fine.

Firmware version: 2.1.0
Model: Ledger Nano X / S

@ledgerhq/hw-app-btc 10.0.5
@ledgerhq/hw-transport-webusb 6.27.16

```
const message = { tokenSn: "1FigxLFf8HkcmPirGWTDcmvoJ8Dh61ujir" }
const signData = {
  ...message
}
const hex = Buffer.from(JSON.stringify(signData)).toString('hex')

const result = await btc.signMessage(this.path, hex)

```

Full message Error
```
Ledger.vue:94 TypeError: "list" argument must be an Array of Buffers
at Function.concat (index.js:399:1)
    at ClientCommandInterpreter.addKnownList (clientCommands.js:231:1)
    at AppClient.eval (appClient.js:141:1)
    at Generator.next (<anonymous>)
    at eval (appClient.js:7:1)
    at new Promise (<anonymous>)
    at __awaiter (appClient.js:3:1)
    at AppClient.signMessage (appClient.js:130:1)
    at BtcNew.eval (BtcNew.js:239:1)
    at Generator.next (<anonymous>)
```

### Expected behavior

it should not throw the error

### Additional context

my vue project demo: https://github.com/SanIP117/ledger-vue-testing

**Comment by bigspider** [comment]
> @bigspider maybe you have an idea? ty ty

No, sorry

**Comment by adrienlacombe-ledger** [comment]
> > @bigspider maybe you have an idea? ty ty
> 
> No, sorry

Thanks!

**Comment by adrienlacombe-ledger** [comment]
@haammar-ledger maybe this rings a bell, ty ty
