### ISSUE TITLE
[Bug]: Unable to resolve certain files in node_modules/@ledgerhq/hw-app-eth

### ISSUE THREAD

**Issue by apfz** [LedgerHQ/ledger-live#3803]
### Impacted Library name

@ledgerhq/hw-app-eth

### Impacted Library version

6.33.6

### Describe the bug

Using hw-app-eth in React Native gives the following errors:

iOS Bundling failed 30226ms
Unable to resolve "@ledgerhq/domain-service/signers/index" from "node_modules/@ledgerhq/hw-app-eth/lib/services/ledger/index.js"

iOS Bundling failed 3412ms
Unable to resolve "@ledgerhq/cryptoassets/data/eip712" from "node_modules/@ledgerhq/hw-app-eth/lib/modules/EIP712/EIP712.utils.js"

iOS Bundling failed 3198ms
Unable to resolve "@ledgerhq/cryptoassets/data/evm/index" from "node_modules/@ledgerhq/hw-app-eth/lib/services/ledger/erc20.js"

### Expected behavior

The @ledgerhq/hw-app-eth is not working out of the box but requires the following modifications:

**node_modules/@ledgerhq/hw-app-eth/lib/services/ledger/index.js:**
-const eip712_1 = __importDefault(require("@ledgerhq/cryptoassets/data/eip712"));
+const eip712_1 = __importDefault(require("@ledgerhq/cryptoassets/lib/data/eip712"));

**node_modules/@ledgerhq/hw-app-eth/lib/modules/EIP712/EIP712.utils.js:**
-const index_1 = require("@ledgerhq/cryptoassets/data/evm/index");
+const index_1 = require("@ledgerhq/cryptoassets/lib/data/evm/index");

**node_modules/@ledgerhq/hw-app-eth/lib/services/ledger/erc20.js:**
-const index_1 = require("@ledgerhq/domain-service/signers/index");
+const index_1 = require("@ledgerhq/domain-service/lib/signers/index");

**Comment by everdimension** [comment]
Facing a lot of similar issues

I'm trying to bundle a library with parcel, getting this error:

_@parcel/core: Failed to resolve '@ledgerhq/domain-service/signers/index' from
'~/projects/hardware-wallet-connection/node_modules/@ledgerhq/hw-app-eth/lib-es/services/ledger/index.js'_

I checked out the source code and this indeed seems like a bundling problem with the ledger libraries. The `signers` package is located at `@ledgerhq/domain-service/lib-es/signers` and not `@ledgerhq/domain-service/signers`

![image](https://github.com/LedgerHQ/ledger-live/assets/5347023/66f70e01-cf1f-473d-941f-35d9925c0eec)
