### ISSUE TITLE
Build problem @ledgerhq/icons-ui

### ISSUE THREAD

**Issue by ruslan-gennadievich** [LedgerHQ/ledger-live#382]
I'm try build:

`pnpm build:lld:deps`

so packets was complete build, but @ledgerhq/icons-ui have this error

`@ledgerhq/icons-ui:build: src/native/BracketleftLight.tsx(13,76): error TS2322: Type '{ children: Element; clipPath: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build: src/native/BracketleftLight.tsx(13,228): error TS2322: Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build: src/native/BracketleftMedium.tsx(13,76): error TS2322: Type '{ children: Element; clipPath: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build: src/native/BracketleftMedium.tsx(13,228): error TS2322: Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build: src/native/BracketleftRegular.tsx(13,76): error TS2322: Type '{ children: Element; clipPath: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build: src/native/BracketleftRegular.tsx(13,228): error TS2322: Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build: src/native/BracketleftThin.tsx(13,76): error TS2322: Type '{ children: Element; clipPath: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build: src/native/BracketleftThin.tsx(13,227): error TS2322: Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build: src/native/BracketleftUltraLight.tsx(13,76): error TS2322: Type '{ children: Element; clipPath: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build: src/native/BracketleftUltraLight.tsx(13,228): error TS2322: Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build: src/native/BracketrightLight.tsx(13,76): error TS2322: Type '{ children: Element; clipPath: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build: src/native/BracketrightLight.tsx(13,230): error TS2322: Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build: src/native/BracketrightMedium.tsx(13,76): error TS2322: Type '{ children: Element; clipPath: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build: src/native/BracketrightMedium.tsx(13,230): error TS2322: Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build: src/native/BracketrightRegular.tsx(13,76): error TS2322: Type '{ children: Element; clipPath: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build: src/native/BracketrightRegular.tsx(13,230): error TS2322: Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build: src/native/BracketrightThin.tsx(13,76): error TS2322: Type '{ children: Element; clipPath: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build: src/native/BracketrightThin.tsx(13,229): error TS2322: Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build: src/native/BracketrightUltraLight.tsx(13,76): error TS2322: Type '{ children: Element; clipPath: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GProps, any, any>> & Readonly<GProps>'.
@ledgerhq/icons-ui:build: src/native/BracketrightUltraLight.tsx(13,230): error TS2322: Type '{ children: Element; id: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:   Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ClipPathProps, any, any>> & Readonly<ClipPathProps>'.
@ledgerhq/icons-ui:build:  ELIFECYCLE  Command failed with exit code 2.
@ledgerhq/icons-ui:build: Error: command finished with error: command (libs/ui/packages/icons) pnpm run build exited (1)
command (libs/ui/packages/icons) pnpm run build exited (1)
`

node -v
v17.7.1

tsc -v
Version 4.1.3

Linux, Ubuntu

**Comment by elbywan** [comment]
Hey @ruslan-gennadievich 👋,

Thanks for reporting the issue, but unfortunately you did not use the proper template.

Please create another one [here](https://github.com/LedgerHQ/ledger-live/issues/new/choose) and please try to format the logs so we can read them easily.

Thanks 👍.
