### ISSUE TITLE
[Bug]: Ledger Live not sending a correct signature when it executes personal_sign

### ISSUE THREAD

**Issue by valeriivanchev** [LedgerHQ/ledger-live#3836]
### Describe the bug

1. The signature provided from Ledger Live after signing a message is not a valid signature. We use ethereum provider 2.8.0 and walletconnect/modal 2.4.5. The decoding works for every other wallet except Ledger Live.
2. When personal sign is executed separately Ledger Live opens WalletConnect v1.

Steps to reproduce the first issue:

1. Connect with WalletConnect v2
2. Send a message
3. Sign message
4. Decode signature

Steps to reproduce the second issue:

1. Open [https://react-dapp-v2-with-ethers.vercel.app/](https://github.com/WalletConnect/walletconnect-monorepo/issues/url)
2. Connect with WalletConnect v2 to Ledger Live
3. Press personal_sign

### Expected behavior

1. To send a valid signature
2. To open and sign with WalletConnect v2

**Comment by crypblizz8** [comment]
Thanks for the raise @valeriivanchev. Can you share your eth provider init setup?
