### ISSUE TITLE
No option to convert Saitama Inu old -> Saitama Inu v2

### ISSUE THREAD

**Issue by dnsoumik** [LedgerHQ/ledger-live#393]
Currently, the Metamask, trust wallets have the option to change the smart contract address resulting the 
migration of Saitama V2,
There is no option currently in the Ledger Live to do the same :(

**Comment by dnsoumik** [comment]
Referring this 
[https://watcher.guru/news/how-to-migrate-tokens-to-saitama-v2](url)
and this official tweet from Saitama Community
[https://twitter.com/WeAreSaitama/status/1531463639445778432](url)

**Comment by elbywan** [comment]
Hey @dnsoumik,

Please pick an [issue template](https://github.com/LedgerHQ/ledger-live/issues/new/choose) and stick to it in the issue description. (also this sounds like a feature request)

Thanks.
