### ISSUE TITLE
[Bug]: TransportInterfaceNotAvailable for Tron TRX App

### ISSUE THREAD

**Issue by Jo-Chris** [LedgerHQ/ledger-live#4017]
### Impacted Library name

@ledgerhq/hw-transport-webusb

### Impacted Library version

6.27.15

### Describe the bug

Error we receive:

_TransportInterfaceNotAvailable: No WebUSB interface found for your Ledger device. Please upgrade firmware or contact techsupport_

After approving from the Tron App on the Ledger, the error occurs:

Reproduce:
```

  async init(): Promise<boolean> {
    if (!this.transport) {
      const support = await webUsbTransport.isSupported();
      if (support) {
        this.transport = await webUsbTransport.openConnected().then((res) => {
          if (!res) return webUsbTransport.create();
          return res;
        });
      } else {
        return Promise.reject(
          new Error("ledger-tron: webusb is not supported")
        );
      }
    }

```

### Expected behavior

It should return a valid `Transport` object.

### Additional context

`webUsbTransport.list()` returns a valid Ledger device, which we can access.

but the USBAlternateInterface shows an invalid InterfaceClass of 3 instead of 255, when printing the TransportWebUSB object.

The Ledger version is up-to-date

Connecting with Ethereum and Polkadot works

**Comment by wsdt** [comment]
++

**Comment by wsdt** [comment]
still an issue

**Comment by wsdt** [comment]
Issue still there

**Comment by wsdt** [comment]
Still open
