### ISSUE TITLE
[Feature]: Add logo Boss Info

### ISSUE THREAD

**Issue by 19668280113** [LedgerHQ/ledger-live#4055]
### Library name

live-desktop @lederhq/live-common

### Describe your feature request

We request to add the Boss Info token for the ledger applications:
Token name: Boss Info
Token symbol: BOSS
Blockchain: ERC20 Ethereum
Token smart contract adress: 0x2e880962a9609aa3eab4def919fe9e917e99073b
Token etherscan.iko link: https://etherscan.io/token/0x2e880962a9609aa3eab4def919fe9e917e99073b
logo:
![b-Favicon-256x256](https://github.com/LedgerHQ/ledger-live/assets/139865828/8a5a9875-6d7c-48d5-b58a-368b299f9e1e)

**Comment by adrienlacombe-ledger** [comment]
https://developers.ledger.com/docs/token/introduction/

**Comment by 19668280113** [comment]
I did this with the request form in your distributed link. But the description for the pull request to add the icon ist out of date. Please check that out.
Thats the reason that we added this issue.

**Comment by adrienlacombe-ledger** [comment]
> I did this with the request form in your distributed link. But the description for the pull request to add the icon ist out of date. Please check that out. Thats the reason that we added this issue.

what is our of date on the icon side of things exactly?

**Comment by 19668280113** [comment]
https://github.com/LedgerHQ/ledger-live-common/pull/1838/commits/bccc67e49f18d2a1edd286d3a2b30ba522a37778
You give this sample to add a pull request. That is out of date.
I contacted the support because it was also not possible to create an new branch on the new source ....
They wrote me that I have to open an issuse.

**Comment by 19668280113** [comment]
From you site:

3. How to add token icon?
When a Token is added in Ledger Live without an icon, it will display the first letter of the token’s name. To add an icon, you must open a Pull Request in the Ledger Live repository. You can [check this PR](https://github.com/LedgerHQ/ledger-live/pull/107) for an example.

You can either create the icon or find it on [cryptoicons.co](http://cryptoicons.co/) or [cryptologos.cc](https://cryptologos.cc/).

Some rules about the icon:

Don’t use Linear gradients, defs, masks, clip-path, filters and inline styles
Only use svg, path, circle, ellipse, rect, polyline, line tags if needed and add fill=”black”
Feel free to look at the other icons to see what is expected.

**Comment by 19668280113** [comment]
If you click check this PR the description there is out of date

**Comment by adrienlacombe-ledger** [comment]
> If you click check this PR the description there is out of date

what do you mean sorry?
