### ISSUE TITLE
[Bug]: Latest version of @ledgerhq/hw-app-eth has breaking changes

### ISSUE THREAD

**Issue by fvictorio** [LedgerHQ/ledger-live#4062]
### Impacted Library name

@ledgerhq/hw-app-eth

### Impacted Library version

6.34.0

### Describe the bug

We have a [`hardhat-ledger`](https://github.com/NomicFoundation/hardhat/tree/main/packages/hardhat-ledger) plugin in our monorepo, and we also have a CI workflow that tries to build and run our tests with the latest versions of all our dependencies.

The latest version of the eth app library broke this workflow because, as far as I can tell, it has some breaking changes (at the very least the `isEIP712Message` was removed from the exports; there might be others).

For now we fixed this by [pinning the version](https://github.com/NomicFoundation/hardhat/pull/4169) we depend on. But, assuming you are following semver, I think this was a mistake.

### Expected behavior

A new minor version shouldn't include breaking changes.

**Comment by Schoonmoeder** [comment]
Also have the issue of missing functions in EVM-tools while hw-app-eth thinks they should be there

example : sortObjectAlphabetically is removed but not exported in evm
removed here https://github.com/LedgerHQ/ledger-live/pull/3924/files#diff-0014e583278c639b19797bb7a95d5ae400802e7f91bb8d44544fd66c7e9fa62f
the pr @pcaversaccio talks about.

![Snip20230719_1](https://github.com/LedgerHQ/ledger-live/assets/11256295/7ee92f2a-3e64-486e-b77d-f3c2e4f7f2dd)

**Comment by lambertkevin** [comment]
Sorry about that guys, no breaking change per se in the new release, just a bundling/releasing problem with the new `evm-tools` lib. 
PR https://github.com/LedgerHQ/ledger-live/pull/4090 is fixing this, a new patch should come soon without the issue 🙏

**Comment by fvictorio** [comment]
> just a bundling/releasing problem with the new `evm-tools` lib

Glad to know it was just that, thanks for the update! I'll re-enable the `^` dependency range after this is fixed then.

**Comment by svarcoder** [comment]
Hi Guys!
I installed only two package and my node v is 18
 "@ledgerhq/cryptoassets": "^7.0.0",
 "@ledgerhq/hw-transport-webusb": "^6.27.7",
 
 But it throws same error 
 Module not found: Can't resolve '@ledgerhq/evm-tools/message/EIP712/index'
 
 Can you tell me how to resolve this and which version I will install for this two package?
<img width="466" alt="Screenshot 2023-07-24 at 5 08 49 PM" src="https://github.com/LedgerHQ/ledger-live/assets/45661122/919b242a-e814-47d4-9193-c73554b49dcb">
<img width="1183" alt="Screenshot 2023-07-24 at 5 08 19 PM" src="https://github.com/LedgerHQ/ledger-live/assets/45661122/15d05e63-2715-45b6-963e-987218687630">
<img width="1059" alt="Screenshot 2023-07-24 at 5 07 55 PM" src="https://github.com/LedgerHQ/ledger-live/assets/45661122/5dadfd14-adad-4f30-a400-c09792034d24">

**Comment by lambertkevin** [comment]
Can you all please try with @ledgerhq/hw-app-eth in version `6.34.1` and let me know if it fixes your issues ?

**Comment by svarcoder** [comment]
> 

I used 6.34.1 v but now this error throws
<img width="1056" alt="Screenshot 2023-07-25 at 1 14 48 PM" src="https://github.com/LedgerHQ/ledger-live/assets/45661122/b29f6435-6c9b-4a5f-8975-5aca9caf6b1c">

**Comment by toxeus** [comment]
@lvndry for me the latest release has fixed the missing dependency issue. To my surprise a dependency on `@ledgerhq/live-network` was introduced. I didn't expect `@ledgerhq/hw-app-eth` to open remote connections. Was that intended?

**Comment by svarcoder** [comment]
> @svarcoder Do you still have the issue ?
Yes. Now the issue is resolved.
