### ISSUE TITLE
[Feature]: Add a custom box to add to balance.

### ISSUE THREAD

**Issue by thalpius** [LedgerHQ/ledger-live#4255]
### Describe your feature request

I would love to see a custom box where I can add my other balances to add to the balance in Ledger Live. Let's say I have 5000 on my bank account or other savings, I can add the 5000 to my total balance so I know how much my balance is in total. A single custom box to enter a balance which adds to the balance in Ledger Live is sufficient.

**Comment by gre** [comment]
I'm afraid it's not in current Ledger Live scope as it only addresses the hardware wallet's accounts, you may need to look for a wider portfolio tracking app.

also please note that we no longer use Github issues for feature requests, but only to track our libraries issues. 
please instead contact our Ledger Support so our product team is informed about this feature request 🙏

Best regards,
gre
