### ISSUE TITLE
[Bug]: require is not defined in browser environment

### ISSUE THREAD

**Issue by martinkingtw** [LedgerHQ/ledger-live#4365]
### Impacted Library name

@ledgerhq/hw-app-eth

### Impacted Library version

6.33.7

### Describe the bug

As title, require is not defined in browser environment, making the package unusable.
The relevant code is https://github.com/LedgerHQ/ledger-live/blob/%40ledgerhq/hw-app-eth%406.33.7/libs/live-network/src/network.ts#L107.

### Expected behavior

The package should be usable in browser environment, instead of only in node environment.

Solution:
import https at the top of the file and remove the require.

**Comment by chronicIntrovert** [comment]
This continues to be true and has not yet been resolved.
