### ISSUE TITLE
[Bug]: @parcel/optimizer-swc: cannot reassign to a variable declared with `const`

### ISSUE THREAD

**Issue by Fell-x27** [LedgerHQ/ledger-live#4368]
### Impacted Library name

@ledgerhq/hw-transport-webusb

### Impacted Library version

6.27.19

### Describe the bug

When I run the command `npm run start`, everything works fine.
However, when I run `npm run build` to obtain a minified, production-ready library, I encounter the following error:
```
> parcel build

🚨 Build failed.

@parcel/optimizer-swc: cannot reassign to a variable declared with `const`

    9181 | 
  > 9182 | $parcel$export($375818ecee1623c3$exports, "default", () => $375818ecee1623c3$export$2e2bcd8739ae039);
  >      |                                                                                                      ^
    9183 | $parcel$export($375818ecee1623c3$exports, "TransportError", () => $9a194f74559621d2$export$8e68de6fb26f2236, (v) => $9a194f74559621d2$export$8e68de6fb26
    9184 | $parcel$export($375818ecee1623c3$exports, "TransportStatusError", () => $9a194f74559621d2$export$78917f4716d96cfe, (v) => $9a194f74559621d2$export$78917


```
I've verified that this is not an error on my side, as even an empty project triggers this issue.

### Expected behavior

`npm run build` runs successfull;

### Additional context

I use the following setup to reproduce an error:
```
import "core-js";
import TransportWebUSB from "@ledgerhq/hw-transport-webusb";
```

**Comment by eventXhorizon** [comment]
same

**Comment by eventXhorizon** [comment]
You could try `parcel build --no-optimize` to skip the optimization check, it works for me

**Comment by Fell-x27** [comment]
> You could try `parcel build --no-optimize` to skip the optimization check, it works for me

It works. Thanks a lot!

**Comment by Fell-x27** [comment]
Bump.

**Comment by Fell-x27** [comment]
bump

**Comment by sam-miele** [comment]
bump
