### ISSUE TITLE
not the newest app

### ISSUE THREAD

**Issue by Kwaskoff** [LedgerHQ/ledger-live#438]
I downloaded the newest version [ledger-live-desktop-2.42.0-linux-x86_64.AppImage](https://github.com/LedgerHQ/ledger-live-desktop/releases/download/v2.42.0/ledger-live-desktop-2.42.0-linux-x86_64.AppImage) here https://www.ledger.com/ledger-live/lld-signatures
but after launch app told me `Found version 2.43.1 (url: ledger-live-desktop-2.43.1-linux-x86_64.AppImage)`
It very strange situation - I go to github for check it, but.. where is releases!? Oo

p.s.
I have just received my first ledger and the impressions are not very pleasant anymore😬

**Comment by valpinkman** [comment]
@Kwaskoff like @gre said we are updating the website with the latest versions. However, this is not the official place to download the latest version of LLD, and it should always be through our website https://www.ledger.com/ledger-live
