### ISSUE TITLE
Add status column on CSV history export

### ISSUE THREAD

**Issue by exAphex** [LedgerHQ/ledger-live#477]
**Describe the bug**

On exporting the operations history as CSV also failed transactions get exported. There is no way to understand from the CSV file alone if a transaction was executed successful or failed. This causes problems on tax reporting tools like cointracking.

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Accounts'
3. Click on 'Operation history'
4. Click on 'Save'
5. Select all accounts, also the ones with failed transactions
6. Click on 'Save'
7. Inspect CSV file

**Expected behavior**

Two possibilities to fix this issue:
1. Do not export failed transactions - this might cause backwards compatibility issues
2. Add a new column "status" indicating if transaction was successful or not.

**Screenshots**

<img width="2260" alt="Bildschirmfoto 2022-06-25 um 02 57 47" src="https://user-images.githubusercontent.com/12788725/175752152-65387647-4123-4eed-95f5-2f24190876ff.png">

![image](https://user-images.githubusercontent.com/12788725/175752163-cb2acb8b-ce0e-49d8-a4c8-f9a0fe4fe5c4.png)

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by GittyGitGitGitty** [comment]
Looks like a feature request, not a bug.
