### ISSUE TITLE
[Feature request] tag releases for desktop/mobile (not just nightly or libs)

### ISSUE THREAD

**Issue by GittyGitGitGitty** [LedgerHQ/ledger-live#478]
**Context**

We need LedgerHQ/ledger-live tagged releases for desktop/mobile.

**Is your feature request related to a problem? Please describe.**

Yes, checkout https://aur.archlinux.org/packages/ledger-live#comment-871188

**Describe the solution you'd like**

Can we get some tags going for the current and future releases of desktop/mobile (not just nightly and libs)?

**Comment by elbywan** [comment]
Hey @GittyGitGitGitty,

Yes, this is planned. See: https://github.com/LedgerHQ/ledger-live/issues/397#issuecomment-1160502781
