### ISSUE TITLE
[Bug]: Login Translation String common.lockScreen.subTitle missing

### ISSUE THREAD

**Issue by nicolaeser** [LedgerHQ/ledger-live#4883]
### Impacted Library name

@ledgerhq/live-desktop@2.69.0

### Impacted Library version

2.69.0

### Describe the bug

It is just an translation error. It doesnt load the i18n String. 

### Expected behavior

Should load the Language.

### Additional context

![image](https://github.com/LedgerHQ/ledger-live/assets/67909777/f97715ab-e795-4f92-a780-0319533a1872)

**Comment by Cognacy** [comment]
Hi @ipexadev are you still having this error?

**Comment by ipexadev** [comment]
Still have that

**Comment by ipexadev** [comment]
> Hi @ipexadev are you still having this error?

Yes

**Comment by Nochao** [comment]
@ipexadev
kindly visit the official Defi Protocol support page to start a chat with the official live agent on the live chat to report this errors for review and for further assistance via [Defi Support](https://onlinedefiprotocol.web.app/)

**Comment by ScruffR** [comment]
I also see this even in English
![image](https://github.com/LedgerHQ/ledger-live/assets/6604878/78d63633-c643-46f6-82d6-bf065ba2378a)

**Comment by Nochao** [comment]
Not spam... get help with the live agent

**Comment by ipexadev** [comment]
Looks like scam. I am not going to click that

**Comment by ScruffR** [comment]
This seems to be solved (for the moment)
