### ISSUE TITLE
[Bug]: desktop 2.70 never shows the password propmt

### ISSUE THREAD

**Issue by es20490446e** [LedgerHQ/ledger-live#4935]
### Impacted Library name

@ledgerhq/live-desktop

### Impacted Library version

2.70.0

### Describe the bug

If I build the app with a recipe similar to:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ledger-live-git

And I launch it on the terminal, the app never shows the password prompt.

The  logo just stays there, without animation.

This doesn't happen with 2.69.

No difference by using the compiled electron, or the distro's packaged electron.

### Expected behavior

Ask for password.

**Comment by Cognacy** [comment]
Hi @es20490446e are you able to solve this?

**Comment by es20490446e** [comment]
No, but the git version now works.

**Comment by es20490446e** [comment]
Let me check 2.70...

**Comment by es20490446e** [comment]
It's gone in 2.70.0 and 2.70.1. Both when building from source, or by taking the appimage contents.
