### ISSUE TITLE
[Bug]: Bluetooth transport disconnect throws an error without calling disconnect listeners

### ISSUE THREAD

**Issue by jordaaash** [LedgerHQ/ledger-live#4958]
### Impacted Library name

@ledgerhq/hw-transport-web-ble

### Impacted Library version

6.27.19

### Describe the bug

Error in the console:

```
monitorCharacteristic.ts:22 Uncaught (in promise) DOMException:
Failed to execute 'stopNotifications' on 'BluetoothRemoteGATTCharacteristic':
GATT Server is disconnected. Cannot perform GATT operations.
(Re)connect first with `device.gatt.connect`.
    at Subscription2.<anonymous> (http://localhost:3000/node_modules/.vite/deps/@ledgerhq_hw-transport-web-ble.js?v=f22ec5a5:3620:20)
```

To reproduce, connect to a Ledger device (I used a Nano X) using the `@ledgerhq/hw-transport-web-ble` transport. Then quit the active app (I used the Solana app). This will cause the transport to disconnect.

This line is reached:
https://github.com/LedgerHQ/ledger-live/blob/64fd193f61866f86bf3839e28220db075312a23d/libs/ledgerjs/packages/hw-transport-web-ble/src/TransportWebBLE.ts#L110

Eventually this line throws the error:
https://github.com/LedgerHQ/ledger-live/blob/64fd193f61866f86bf3839e28220db075312a23d/libs/ledgerjs/packages/hw-transport-web-ble/src/monitorCharacteristic.ts#L22

This prevents any `transport.on('disconnect', ...)` listener from being called here:
https://github.com/LedgerHQ/ledger-live/blob/64fd193f61866f86bf3839e28220db075312a23d/libs/ledgerjs/packages/hw-transport-web-ble/src/TransportWebBLE.ts#L113

### Expected behavior

Uncaught errors should not be thrown. The transport is already disconnected, so internal errors while disconnecting or tearing down observers should be expected and handled gracefully. Any listeners of the transport disconnect event should be emitted to.

**Comment by jordansexton** [comment]
Not stale, this is a bug.

**Comment by haammar-ledger** [comment]
@alexandremgo FYI

**Comment by jordaaash** [comment]
This is a bug and is not stale. Please take a look.
