### ISSUE TITLE
Fedora 36 Wayland Blank GUI

### ISSUE THREAD

**Issue by Blookebleep** [LedgerHQ/ledger-live#511]
**Describe the bug**
 Loading the Ledger Live app image on Fedora 36 running the Wayland display server returns a blank black GUI.

**To Reproduce**

1. Load up Fedora 36 and ensure you are running the OS using the Wayland display server.
2. Download and make the app image executable.
3. Run the appimage in terminal
4. See error:
 libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

**Expected behavior**

 As with other OS's running Wayland the Ledger Live applications GUI should display.

**Screenshots**
VM vs HOST both running wayland. HOST Fedora 36 (Workstation Edition). VM Pop!_OS 22.04 LTS

![VMvsHOST](https://user-images.githubusercontent.com/56186132/176339990-09a49cb0-9f0d-4bdb-85b8-ac63359e502c.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36 (Workstation Edition)
 - CPU Ryzen 7 3700X
 - GPU: GTX 1070TI 

**Additional context**
I have tried to reproduce this using a Pop_OS! virtual machine running wayland. See in screenshot the comparison between the host and the VM.
Note that Nvidia gpu's sometimes have trouble on Wayland. I asked a person on discord with an Nvidia GPU to reproduce this and got the same error.

**Comment by elbywan** [comment]
Hey @Blookebleep,

Thanks for reporting the problem 🙏 !

I won't lie to you, we do not have this kind of very specific setup at Ledger and there is very little chance that we find the time to look into it.

I will keep the issue open in case an external contributor finds the time to look into it.

**Comment by Blookebleep** [comment]
I understand! Thank you for taking the time to reply!
