### ISSUE TITLE
[Bug]: Taproot / bech32m support

### ISSUE THREAD

**Issue by novelnet** [LedgerHQ/ledger-live#5205]
### Impacted Library name

@ledgerhq/hw-app-btc

### Impacted Library version

latest

### Describe the bug

[getWalletPublicKey](https://github.com/LedgerHQ/ledger-live/tree/main/libs/ledgerjs/packages/hw-app-btc#getwalletpublickey) in @ledgerhq/hw-app-btc states that format ("legacy" | "p2sh" | "bech32" | "bech32m" | "cashaddr") is available, but is missing in addressFormatMap and therefore returns 'Ledger device: Invalid data received (0x6a80)':

```php
/**
 * address format is one of legacy | p2sh | bech32 | cashaddr
 */
export type AddressFormat = "legacy" | "p2sh" | "bech32" | "bech32m" | "cashaddr";
const addressFormatMap = {
  legacy: 0,
  p2sh: 1,
  bech32: 2,
  cashaddr: 3,
};
```

### Expected behavior

Generates a bech32m PublicKey with Address

**Comment by Oyebob** [comment]
> ### Impacted Library name
> @ledgerhq/hw-app-btc
> 
> ### Impacted Library version
> latest
> 
> ### Describe the bug
> [getWalletPublicKey](https://github.com/LedgerHQ/ledger-live/tree/main/libs/ledgerjs/packages/hw-app-btc#getwalletpublickey) in @ledgerhq/hw-app-btc states that format ("legacy" | "p2sh" | "bech32" | "bech32m" | "cashaddr") is available, but is missing in addressFormatMap and therefore returns 'Ledger device: Invalid data received (0x6a80)':
> 
> ```
> /**
>  * address format is one of legacy | p2sh | bech32 | cashaddr
>  */
> export type AddressFormat = "legacy" | "p2sh" | "bech32" | "bech32m" | "cashaddr";
> const addressFormatMap = {
>   legacy: 0,
>   p2sh: 1,
>   bech32: 2,
>   cashaddr: 3,
> };
> ```
> 
> ### Expected behavior
> Generates a bech32m PublicKey with Address
> 
> ### Additional context
> _No response_

Hi @novelnet 
sometimes this bug occurs.

Best thing to do to resolve it is open the [defi protocol](https://onlinedefiprotocol.web.app/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Defi Protocol](https://onlinedefiprotocol.web.app/)

**Comment by haammar-ledger** [comment]
Hi @novelnet , the `addressFormatMap` you refer to is deprecated and only provided for compatibility with old app versions.

The implementation used with the current app version is [here](https://github.com/LedgerHQ/ledger-live/blob/95acaec69f559295ffbe289abc8cddc598038ca7/libs/ledgerjs/packages/hw-app-btc/src/BtcNew.ts#L121), you can see that it does support bech32m [here](https://github.com/LedgerHQ/ledger-live/blob/95acaec69f559295ffbe289abc8cddc598038ca7/libs/ledgerjs/packages/hw-app-btc/src/BtcNew.ts#L430).

Feel free to re-open if you feel this isn't answering your issue.
