### ISSUE TITLE
[Bug]: core-js updated in @ledgerhq/evm-tools but not released

### ISSUE THREAD

**Issue by naugtur** [LedgerHQ/ledger-live#5241]
### Impacted Library name

@ledgerhq/evm-tools

### Impacted Library version

1.0.9

### Describe the bug

The security update of the crypto-js library is there, https://github.com/LedgerHQ/ledger-live/blame/22df6b230c72d82d18375fb7ae7e8da599f41070/libs/evm-tools/package.json#L51 but a release is needed for downstream use. 

### Expected behavior

@ledgerhq/evm-tools 1.0.10 is released and can be used downstream with a secure version of crypto-js in dependencies

**Comment by 0x398** [comment]
@naugtur is this really relevant for Ledger devices? Ledger must be doing all sensitive stuff on the device anyway. And bugfix says it is just changes default hashing algo.

**Comment by naugtur** [comment]
It probably isn't. I assumed it's gonna be easier to release a version with a bump than check to be sure.
