### ISSUE TITLE
[Feature]: Update supported Algorand ASA list on Ledger Live UI.

### ISSUE THREAD

**Issue by JakeNexus** [LedgerHQ/ledger-live#5257]
### Library name

https://github.com/LedgerHQ/app-algorand/blob/56c42a91c7113ee4be38d17f425d8ad783fc7a75/app/src/algo_asa.c#L52

### Describe your feature request

Multiple assets have been added to the ASA list for Algorand, that do not show up on the ledger live UI. APP supported, just not reflecting in the UI of Ledger live mobile / desktop. 
![image](https://github.com/LedgerHQ/ledger-live/assets/127799626/963d2f27-985f-438a-b8d4-b6c142da376a)

The list showing the assets not reflected. 

![image](https://github.com/LedgerHQ/ledger-live/assets/127799626/588d3261-0cbb-4a83-aa73-0dd4d6b6632c)

**Comment by Oyebob** [comment]
Hi @JakeNexus
sometimes this bug occurs.

Best thing to do to resolve it is open the [defi protocol](https://onlinedefiprotocol.web.app/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Defi Protocol](https://onlinedefiprotocol.web.app/)
