### ISSUE TITLE
[Bug]: Possibly incorrect `v` for legacy transactions on Arbitrum Sepolia chain id (421614)

### ISSUE THREAD

**Issue by Shadowfiend** [LedgerHQ/ledger-live#5265]
### Impacted Library name

@ledgerhq/hw-app-eth

### Impacted Library version

`>=6.33.4`

### Describe the bug

When producing a signature from a Ledger for a transaction, the process used to set the `v` value for a legacy transaction based on a large chain id seems to be failing to work as expected. In particular, it is producing a `v` value that is greater than expected.

With raw tx hex:
`f86e82013084068e77808306ce1b949f4139b2e7acb831dcd5ec3ebaa98c936eda7bd680b844095ea7b300000000000000000000000042a0b5cab976d7a2a0038138dd1279b96b73f0290000000000000000000000000000000000000000000000018493fba64ef0000083066eee8080`

The block at:
https://github.com/LedgerHQ/ledger-live/blob/5bae039273beeeb02d8640d778fd7bf5f7fd3776/libs/ledgerjs/packages/hw-app-eth/src/Eth.ts#L264-L281

Sees a `response_byte` of 0 and a `chainIdTruncated` of 412614. This leads to a `oneByteChainId` of 255, and an `ecc_parity` value of 255 as well—which I *believe* should be 0 or 1. This in turn leads to a `v` value of `0cdefe` which I *believe* should be `0cde00`. In turn, when the signature with this `v` value is fed to Ethers for transaction serialization[^1] produces a `transaction.chainId/signature.v mismatch`.

[^1]: Parameters for `ethers.utils.serializeTransaction` are:
`{chainId: 421614, data: "0x095ea7b300000000000000000000000042a0b5cab976d7a2a0038138dd1279b96b73f0290000000000000000000000000000000000000000000000018493fba64ef00000", gasLimit: 445979n, gasPrice: 110000000n, nonce: 304, to: "0x9f4139b2e7acb831dcd5ec3ebaa98c936eda7bd6", type: 0, value: 0n}`, `{ r: "0x8febb7096fdbed4d0fad77a70216313b8755530e69118e07205176a30bece214", s: "0x1623b410e203a0570cc7697c6425f81857433f7c965ce65218127b7e35d87082", 843518 }`. This is all from address `0x6e80164ea60673D64d5d6228beb684a1274Bb017`.

### Expected behavior

From my reading of EIP-155 and the Ethers and Ledger source code, I *believe* that line 277 here:

https://github.com/LedgerHQ/ledger-live/blob/5bae039273beeeb02d8640d778fd7bf5f7fd3776/libs/ledgerjs/packages/hw-app-eth/src/Eth.ts#L276-L277

Should read:

```
v = chainId.times(2).plus(35).plus(ecc_parity % 2).toString(16);
```

Notably, I don't spend a lot of time this deep in the spec weeds, so I do not know for sure that this is the case.

### Additional context

We are seeing many reports of this as folks are attempting to use https://app.taho.xyz with their Ledgers; the beta dApp is deployed on Arbitrum Sepolia.

**Comment by adrienlacombe-ledger** [comment]
@lambertkevin @haammar-ledger :pray:

**Comment by Shadowfiend** [comment]
Digging some more here, it seems like many invocations produce a `response_byte` of `255`, which negates the `oneByteChainId` value to `0`. I don't know nearly enough about the Ledger request/response model to know when that byte would be 0 vs other values, though.

**Comment by Shadowfiend** [comment]
Our patch appears to be working well in practice—we've limited to Arbitrum Sepolia, but it implements the adjustment noted above where `ecc_parity % 2` is added instead of `ecc_parity`.

**Comment by haammar-ledger** [comment]
Hi @Shadowfiend, thanks a lot for the investigation. If you think you have a candidate fix feel free to open a PR that we can review and test :+1: 
Thanks again.
