### ISSUE TITLE
[Bug]: Flare (FLR) Version 1.10.3 • 0.6 KB cannot be installed

### ISSUE THREAD

**Issue by hitchhooker** [LedgerHQ/ledger-live#5323]
### Impacted Library version
aur/ledger-live-bin 2.69.0-1

### Describe the bug

Trying to install Flare (FLR) Version 1.10.3 • 0.6 KB to Ledger Nano S plus, it repeats install 3 times and gives error.

Something went wrong. Please reconnect your device
Ledger device: UNKNOWN_ERROR (0x6811)

### Expected behavior

I thought all apps in store are tested to work before distribution.

### Additional context

0.6KB wallet version seems also be quite off the normal.

**Comment by aelmilligy-ledger** [comment]
Hi @hitchhooker,

I managed to reproduce your behaviour. You have to update the Ethereum App and then give a try to install the Flare App, it should work.
