### ISSUE TITLE
[Feature]: Disabling telemetry/bug reports/analytics through env variables/cmdline args

### ISSUE THREAD

**Issue by surfaceflinger** [LedgerHQ/ledger-live#5324]
### Describe your feature request

Hi,

Ledger Live is riddled by 3rd party tracking SDKs like Sentry. Also, toggles for things like Bug reports and Analytics are On by default.
I'm fine with Ledger Live doing regular communication with regular nodes/RPCs but I'm not fine with actual tracking done BY DEFAULT and I'm surprised that at this point there's no Ledger Live privacy oriented fork like there's for example VSCodium for VS Code.

I think that a good solution for this would be introducing support for runtime environment variables like LEDGER_LIVE_ANALYTICS/LEDGER_LIVE_BUG_REPORTS which would either control the default settings (overridable by changing them manually in GUI, perhaps with a confirmation window? would prevent situations like enabling them by a mistake) or would permanently disable analytics/tracking if set to false.

I have no idea how Ledger related software other than Ledger Live Desktop works, but if other official software does tracking too, perhaps these env variables could be made universal for all components.

Also - in case this will actually get considered - does disabling bug reports and analytics in settings actually turn off ALL of tracking/telemetry/bug reporting that isn't regular RPC/node connection?

**Comment by surfaceflinger** [comment]
still important to me.

**Comment by surfaceflinger** [comment]
how do you unstale this? quite pathetic to autoclose issues.

**Comment by surfaceflinger** [comment]
Still important to me :p

**Comment by surfaceflinger** [comment]
Still important to me

**Comment by surfaceflinger** [comment]
Still important to me

**Comment by AnthonyHad** [comment]
Hi @surfaceflinger

Apologies for the delay in getting back to you. We understand the importance of your concerns and appreciate your patience.

We’re excited to inform you that in the forthcoming updates for both Ledger Live Mobile and Ledger Live Desktop, we are enhancing our approach to user privacy and data sharing. A significant update includes the introduction of an explicit analytics consent mechanism. This means that upon updating to the latest versions, you will be prompted to review and update your preferences regarding the sharing of analytics and personalised recommendations data with us.

We are committed to ensuring that your choice to opt-out of data sharing is fully respected. To this end, we’re taking careful steps to ensure that when a user decides to opt-out, no data will be shared with SDKs or any third-party services.

As we roll out these updates, we welcome any feedback or questions you may have about these changes or any other aspect of our services.


Thank you once again for your patience and understanding.

**Comment by surfaceflinger** [comment]
That's great to hear, so far I've been quite disappointed with what Ledger Live has been doing by default and actually planned to switch to Trezor after they released Safe 3.

In this case, if what you're describing is true - I'm hyped =) Let's keep the issue open for now and I'll close it after getting my hands on the future release.

**Comment by surfaceflinger** [comment]
unstale

**Comment by surfaceflinger** [comment]
Hi @AnthonyHad,
is this feature finally out? 
I noticed this in my app.json
```
"hasSeenAnalyticsOptInPrompt":false,
```

is this simply not going to show up if I already had analytics disabled or is this feature just not fully enabled yet?

**Comment by surfaceflinger** [comment]
unstale

**Comment by surfaceflinger** [comment]
bump

**Comment by djGLiTCH** [comment]
Thanks for keeping this going @surfaceflinger

**Comment by surfaceflinger** [comment]
Really annoyed with how they handle GitHub issues, just ignore everything and hope the "stale" bot kicks in :)

**Comment by AnthonyHad** [comment]
@surfaceflinger Hello. Thank you for your patience 🙏 

It took more time than expected but after several tests and analysis we are finally **gradually** rolling out the analytics consent prompt to all new and existing users of Ledge Live. You can expect to see this prompt soon. 

We hope this will address all of your concerns. Please let us know if you have any feedback.

**Comment by surfaceflinger** [comment]
😎🤙

**Comment by surfaceflinger** [comment]
we did it reddit

![image](https://github.com/user-attachments/assets/99cecb3b-6065-4da3-a260-02ad68ef888e)
![image](https://github.com/user-attachments/assets/edd1065b-071b-4c3d-b2c9-7fd4dbcbce92)
