### ISSUE TITLE
ledger-live-desktop-2.68.1.sha512sum (1)-1.txt

### ISSUE THREAD

**Issue by Josemoe** [LedgerHQ/ledger-live#5402]
Shared by a full-featured free reader app - All Document Reader: https://st.deepthought.industries/vuA32i![ledger-live-desktop-2.68.1.sha512sum (1)-1.txt](https://github.com/LedgerHQ/ledger-live/files/13325196/ledger-live-desktop-2.68.1.sha512sum.1.-1.txt)

Can you fix or correct any issues or errors please

**Comment by FibreFoX** [comment]
spam?
