### ISSUE TITLE
[Bug]: Class constructor Transport cannot be invoked without 'new'

### ISSUE THREAD

**Issue by bucko13** [LedgerHQ/ledger-live#5503]
### Impacted Library name

@ledgerhq/hw-transport-webusb, @ledgerhq/hw-transport

### Impacted Library version

6.28.8

### Describe the bug

When using this library in another library, we were running into an error whenever we needed to instantiate a transport. It wasn't clear what was causing the issue as there didn't seem to be a change in the webusb library between when it was working and when it wasn't. It turns out that if we locked hw-transport to 6.28.1 then the ledger device communication would work again.

This is the PR that fixed it in our library unchained-wallets: https://github.com/unchained-capital/unchained-wallets/pull/137

### Expected behavior

Should be able to instantiate a new web usb transport

**Comment by bucko13** [comment]
I’d like to keep this issue open and curious if there has been an opportunity to address it. Currently the only way we are able to keep libraries building without error is pinning an upstream dependency in any environment it’s used.

**Comment by bucko13** [comment]
Any update on this? We're still seeing this issue and it's very disruptive to active development.

**Comment by bucko13** [comment]
I got a notification that this is going stale but it’s still an active problem for us in production environments. Pinning upstream dependencies is a patch for now but makes it very hard to maintain.

**Comment by bucko13** [comment]
Still a very active issue as far as I’m aware. Would love an update on this so we can update our ledger dependencies.

**Comment by sirtimid** [comment]
We had to override the dependency to 6.28.1 so this is still an issue.

**Comment by bucko13** [comment]
Still active. Awaiting response so we can upgrade libraries.

**Comment by bucko13** [comment]
Has this issue actually been resolved? We still have to keep our ledger dependencies pinned to avoid breaking builds.
