### ISSUE TITLE
CACHE Gold Token (CGT) is suddenly missing from all Ledger devices and apps

### ISSUE THREAD

**Issue by cache-gold** [LedgerHQ/ledger-live#554]
Hi, Our token CACHE GOLD - CGT appears to be come back as delisted and countervalues disabled, which has caused customers using Ledger to be worried about the token. Our token is still growing and can be viewed here - https://coinmarketcap.com/currencies/cache-gold/

https://raw.githubusercontent.com/LedgerHQ/ledger-live-desktop/v2.39.2/cryptoassets.md
https://raw.githubusercontent.com/LedgerHQ/ledgerjs/master/packages/cryptoassets/data/erc20.js

Would be grateful, if someone can point me in the right direction to fix this via a PR. Thanks!

https://etherscan.io/token/0xf5238462e7235c7b62811567e63dd17d12c2eaa0

This previous issue was archived without reply - https://github.com/LedgerHQ/ledgerjs/issues/804

@seigneur

**Comment by cache-gold** [comment]
This should not be marked stale because it is not fixed.

**Comment by gre** [comment]
@cache-gold thanks for your github issue, we're going to resynchronise our tokens because it was internally fixed ~a month ago but it didn't reach Ledger Live yet.

**Comment by gre** [comment]
mmh actually it's going to be included in future releases. It is up to date already – at least on develop branch – https://raw.githubusercontent.com/LedgerHQ/ledger-live/develop/apps/ledger-live-desktop/cryptoassets.md
