### ISSUE TITLE
Clicking switch button for asset in portfolio doesn't update statistics

### ISSUE THREAD

**Issue by net147** [LedgerHQ/ledger-live#556]
**Describe the bug**

Clicking switch button for asset in Portfolio doesn't update balance in bold and price change to match the units for the graph.

**To Reproduce**

1. Click on Portfolio in the left sidebar
2. Click on an asset under Asset
3. Click the switch button next to the balance

**Expected behavior**

Balance in bold and price change should match the units for the graph.

**Desktop:**
 - OS: Windows 10
 - Application version: 2.43.1

**Additional context**

Clicking Accounts in the left sidebar, clicking an account and clicking the switch button works as expected. It just doesn't work from Portfolio where an asset may be aggregating multiple accounts. The last release where it was working as expected is 2.40.0.

**Comment by net147** [comment]
Any update?

**Comment by gre** [comment]
Hi and sorry for the delay in answering on this Github issue.
We only use Github issues for developers topics (typically on topics that concerns our SDK, libraries,..). For questions, feature requests or Ledger Live issues, please directly go through our Customer Support: https://support.ledger.com/

Thanks
