### ISSUE TITLE
[Bug]: navigator.product is deprecated

### ISSUE THREAD

**Issue by n4l5u0r** [LedgerHQ/ledger-live#5758]
### Impacted Library name

@ledgerhq/live-network

### Line
https://github.com/LedgerHQ/ledger-live/blob/2e2797528ba91eafa42d99ab6d6264dd7265c68c/libs/live-network/src/network.ts#L103

### Impacted Library version

1.1.10

### Describe the bug

'product' is deprecated.ts(6385)
lib.dom.d.ts(15989, 8): The declaration was marked as deprecated here.
(property) NavigatorID.product: string
@deprecated — [MDN Reference][(vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/product)

### Expected behavior

the condition must be respected in ReactNative execution, it's not anymore

**Comment by haammar-ledger** [comment]
Will be solved with https://github.com/LedgerHQ/ledger-live/pull/5979
