### ISSUE TITLE
[Bug]: Installing Meter app fails

### ISSUE THREAD

**Issue by xiaohanzhu** [LedgerHQ/ledger-live#5808]
### Describe the bug

I was trying to install Meter app 1.10.3 to my ledger Nano S plus through the latest Ledger live 2.73.0.  The installer kept on giving me UNKNOWN_ERROR (0x6811) during the installation process and fail at the end.  
I am from Meter team.  Please let me know if there is any support needed from our end 

### Expected behavior

the Meter App should be installed properly
<img width="1794" alt="image" src="https://github.com/LedgerHQ/ledger-live/assets/9540395/6f0d951d-716e-43fa-8df0-9769a7045183">

**Comment by Trustwallet78** [comment]
We are sorry for the inconvenience

**Comment by aelmilligy-ledger** [comment]
Hi @xiaohanzhu,

Did you install the ethereum app ? The Meter app needs the ethereum already installed as it relays partly on it. Here some documentation if you need more details: https://support.ledger.com/hc/en-us/articles/4407690578321-Solving-Error-0x6a83-or-0x6811-?support=true 

Best regards.
