### ISSUE TITLE
Please remove, or enable removal of, the default "Install app" and "Control Center" icons.

### ISSUE THREAD

**Issue by sudoforge** [LedgerHQ/ledger-live#608]
These icons are superfluous, do not provide any functionality, and provide information to users that is learned very quickly. As such, I imagine that many users would prefer to be able to remove them (or not have them displayed at all).

**Comment by sudoforge** [comment]
I'm not sure this belongs here, because I can't find any record of the applications outside of translations for the names and descriptions (in any repo under the `LedgerHQ` organization). Are they baked into the firmware?

**Comment by gre** [comment]
could you provide a screenshot of the part you are referring too? I'm not sure to understand precisely the issue. thanks

**Comment by sudoforge** [comment]
@gre This request is about the `Install app` and `Control Center` icons that are on the hardware device's interface. These provide no functionality for the user, and are instead just providing instructions that experienced users do not need.

I was not able to find a more appropriate repository in which to submit this issue. Please let me know if there is a more appropriate place to submit this, and I'll be happy to do so.

**Comment by gre** [comment]
Sorry for my delay in the answer. The best place for this feedback would be to send it on https://support.ledger.com/ 
Thanks
