### ISSUE TITLE
[Bug]: Argument of type 'RequestInfo' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by domiiinik** [LedgerHQ/ledger-live#6623]
### Describe the bug

trying to build the app as in readme via pnpm build:lld gives an error:

@ledgerhq/live-common:build: $ pnpm tsc --project src/tsconfig.json
@ledgerhq/live-common:build: src/families/solana/api/chain/index.ts:87:18 - error TS2345: Argument of type 'RequestInfo' is not assignable to parameter of type 'string'.
@ledgerhq/live-common:build:   Type 'URLLike' is not assignable to type 'string'.
@ledgerhq/live-common:build: 
@ledgerhq/live-common:build: 87           logger(url, options);
@ledgerhq/live-common:build:                     ~~~
@ledgerhq/live-common:build: 
@ledgerhq/live-common:build: 
@ledgerhq/live-common:build: Found 1 error in src/families/solana/api/chain/index.ts:87
@ledgerhq/live-common:build: 
@ledgerhq/live-common:build: Error: 
@ledgerhq/live-common:build:     at file:///home/dominik/Downloads/ledger-live/libs/ledger-live-common/scripts/build-ts.mjs:18:10
@ledgerhq/live-common:build:     exit code: 2 (Misuse of shell builtins)
@ledgerhq/live-common:build:  ELIFECYCLE  Command failed with exit code 1.
@ledgerhq/live-common:build: ERROR: command finished with error: command (/home/dominik/Downloads/ledger-live/libs/ledger-live-common) pnpm run build exited (1)
command (/home/dominik/Downloads/ledger-live/libs/ledger-live-common) pnpm run build exited (1)

### Expected behavior

no error during the build

**Comment by gre** [comment]
What node version are you using? I suspect something is wrong with your setup because our CI manage to build live-common without this error 🤔
