### ISSUE TITLE
[Bug]: Polkadot Send More than 1 DOT Applies to 11 DOT

### ISSUE THREAD

**Issue by aidan-elliot** [LedgerHQ/ledger-live#6838]
### Describe the bug

When sending between 11-11.99 DOT from the Ledger Live Desktop, an error popup indicated more than 1 DOT needs to be sent and will not let you proceed to send. If max amount of DOT is between 11-11.99 and you click the "send max" switch, you are able to send, but the transaction will fail.

### Expected behavior

The error popup should only be displayed if sending less than 1 DOT, it should not apply to 11 DOT.

**Comment by Devassistance** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
