### ISSUE TITLE
[Bug]: Incompatible with @ledgerhq/errors

### ISSUE THREAD

**Issue by josephchung796** [LedgerHQ/ledger-live#6882]
### Impacted Library name

@ledgerhq/hw-transport, @ledgerhq/errors

### Impacted Library version

6.30.5, 6.16.4

### Describe the bug

Error type - TransportRaceCondition used in @ledgerhq/hw-transport@6.30.5 doesn't exist in @ledgerhq/errors@6.16.4.

### Expected behavior

If I use @ledgerhq/errors@6.16.3, it works fine with @ledgerhq/hw-transport@6.30.5.

**Comment by josephchung796** [comment]
It would be great to fix this issue until this weekend.

**Comment by coredomain** [comment]
You could temporarily solve it by adding this in line 91 export const
TransportRaceCondition = createCustomErrorClass("TransportRaceCondition");

in the index.js found at ***@***.***/errors/lib-es/index.js

Builds out of your dev environments will not work because the packages will
be restored from public repos. Another solution you can try is to create
your local repository and point your restore endpoint to it. Just make sure
you apply this change in your local repo, and later, when the issue is
fixed, update your local repos with the public.

I know you did not ask, but other people outhere.

**Comment by josephchung796** [comment]
Ok, thanks for your help, @coredomain

**Comment by josephchung796** [comment]
Once this issue is permanently fixed in public repo, please let me know.
So that I can update my project and close this issue.

**Comment by gre** [comment]
@aussedatlo fyi it may relates to your changes in https://github.com/LedgerHQ/ledger-live/pull/6394 , i just don't understand how it's possible that hw-transport is published but not errors , libs are supposed to be published together, unless we forgot to declare the changes using changeset for errors lib?

**Comment by aussedatlo** [comment]
The changeset for #6394 does not specify modifications to the 'errors' package, so it was not published as intended.

**Comment by aussedatlo** [comment]
Like @devfive suggest here: https://github.com/LedgerHQ/ledger-live/pull/6394#issuecomment-2072125976

We should bring back `TransportRaceCondition` with depreciation notice to avoid breaking changes.

**Comment by Davincible** [comment]
https://github.com/anza-xyz/wallet-adapter/pull/949

Becoming a big issue for the community as building anything with `@solana/wallet-adapter-wallets` is now broken. Would be massive headache saver to get this resolved

**Comment by Tilakraj0308** [comment]
Any updates on this?? Please if anyone knows

**Comment by josephchung796** [comment]
Thanks very much.

**Comment by PdroCorrea** [comment]
This still isn't on npm, after reading this thread I installed 16.4 and it didn't work after installing 16.3 finally got it work! Just as fyi until new package is out, for anyone still having this issue.

**Comment by coredomain** [comment]
Thanks for the updateSent from my iPhoneOn Jun 3, 2024, at 6:35 PM, PdroCorrea ***@***.***> wrote:﻿
This still isn't on npm, after reading this thread I installed 16.4 and it didn't work after installing 16.3 finally got it work! Just as fyi until new package is out, for anyone still having this issue.

**Comment by josephchung796** [comment]
This issue still exists on npm package.
![image](https://github.com/LedgerHQ/ledger-live/assets/167800418/655133ac-afb6-464f-9429-ade07696aa30)

**Comment by roguzh** [comment]
It looks like `hw-transport`'s dependency is still not updated and keep causing this error.

**Comment by svein1010** [comment]
`@ledgerhq/errors` has BREAKING CHANGEs but it just update with the minor version. Could you please make `@ledgerhq/transport` works fine with minor version change such as `@ledgerhq/errors@^6.10.0` ?
