### ISSUE TITLE
Ability to get application app in use

### ISSUE THREAD

**Issue by vaske** [LedgerHQ/ledger-live#695]
I'm seeking the ability to get information on which app is running in the Ledger device, need this to be able to know if the user using the EVM app or some native token app, is this even possible?

**Comment by gre** [comment]
Yes, here is the code that can be used to get the app name and version. https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledger-live-common/src/hw/getAppAndVersion.ts

**Comment by vaske** [comment]
@gre isn't https://github.com/LedgerHQ/ledger-live-common deprecated? Do you plan to move that function to some other location or?
