### ISSUE TITLE
[Bug]: Misleading "Stake" Button Text in Tezos Delegation Feature

### ISSUE THREAD

**Issue by jevonearth** [LedgerHQ/ledger-live#7002]
### Impacted Library name

@ledgerhq/coin-tezos

### Impacted Library version

0.3.12

### Describe the bug

In the Tezos protocol, it is possible to "Delegate" the baking/validation rights of our account to a network "Baker". Baker is the Tezos term for a POS Validator.

In the Ledger Live Wallet App, there is a call-to-action button labeled "Stake". The use of the word stake in this context up until now has been a misnomer, as "Stake" and "Delegate" are occasionally substituted for each other.

On Tuesday, June 4th, the Tezos blockchain protocol will update to a new protocol named "Paris" (more details [here](https://www.tezosagora.org/proposal/PtParisBQscdCm6Cfow6ndeU6wKJyA3aV1j4D3gQBQMsTQyJCrz/123)).

This protocol introduces a new feature named "Staking" that exists alongside "Delegation".

A quote from the Paris proposal description is as follows:
> The Paris proposals introduce a new role — staker — in addition to delegate (baker) and delegator. Stakers contribute to their chosen baker’s security deposit without the baker taking custody of their funds, for which they are allocated a proportional share of rewards automatically by the Tezos economic protocol. Unlike liquid delegation, staked funds are frozen and are subject to slashing, in proportion to their contribution to their chosen baker’s deposit.

Given this new feature, the misnomer of using the word "Stake" in place of "Delegation" becomes more problematic.

### Expected behavior

The "Stake" button text should be renamed to "Delegate" so that Ledger Live Wallet users are not misled into thinking they would put their tokens at risk when delegating.

### Additional context

This change is critical with the introduction of the new "Staking" feature in the Tezos "Paris" protocol update. Clarifying the terminology will prevent confusion and potential misuse of the delegation feature by users.

**Comment by songproducer** [comment]
This needs to be a high priority
