### ISSUE TITLE
Ledger Live shows fees as Rewards (for Atom)

### ISSUE THREAD

**Issue by grobmeier** [LedgerHQ/ledger-live#721]
When a reward was received with Ledger Live, Ledger Live shows the fees as "received reward".

<img width="484" alt="image" src="https://user-images.githubusercontent.com/873786/180492346-0e9739d7-27ce-48b9-9aff-f25ec695c448.png">

In this image the reward is 0,005, but that's the fees. In fact, the reward is 0,18:

https://atomscan.com/transactions/0C057A49DC51AE248E80CEB7854130BFCD1BD72685DE3B43C8784FD25391828D

Also the latest operations show this reward:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/873786/180492950-c85f481b-bd82-462d-b1b1-9992f086270c.png">

 - OS: MacOS, Ledger Live
 - Device: also liek this on an IPhone 7+

**Comment by grobmeier** [comment]
Hello, the issue is still persisting. Any comments are welcome, as it is pretty annoying to be honest :) Thanks!

**Comment by gre** [comment]
Hi and sorry for the delay in answering on this Github issue.
We only use Github issues for developers topics (typically on topics that concerns our SDK, libraries,..). For questions, feature requests or Ledger Live issues, please directly go through our Customer Support: https://support.ledger.com/

Thanks

**Comment by grobmeier** [comment]
Thanks @gre for fixing this anyway. Just checked it out and it looks much better now. I will follow the support link in case of issues, but in this case I thought reporting an obvious bug would help the developers most. Without me having to go to the burdens of the support team first.
