### ISSUE TITLE
Can someone add support for BitTorrent, WINK, Klever coins

### ISSUE THREAD

**Issue by dnsoumik** [LedgerHQ/ledger-live#727]
Currently no option to check the current prices of BitTorrent, Wink or Klever coins in Ledger Live

**Comment by dnsoumik** [comment]
![Screenshot from 2021-01-27 23-19-36](https://user-images.githubusercontent.com/30685539/180658459-5369fe56-8d78-4651-884c-d18734f29486.png)

**Comment by dnsoumik** [comment]
![Screenshot from 2022-07-24 22-37-44](https://user-images.githubusercontent.com/30685539/180658486-f219058b-07db-4f96-bdcc-dffea9759222.png)

**Comment by gre** [comment]
Hey, thanks for this ticket.
As we don't directly manage the token in this repository, could you please contact our tech support on https://support.ledger.com/ ?
Thanks
