### ISSUE TITLE
[Bug]: TransportRaceCondition was not found in @ledgerhq/errors

### ISSUE THREAD

**Issue by josephchung796** [LedgerHQ/ledger-live#7290]
### Impacted Library name

@ledgerhq/hw-transport

### Impacted Library version

6.30.5

### Describe the bug

![image](https://github.com/LedgerHQ/ledger-live/assets/167800418/8d478af5-328a-4558-a4ca-a6d4853bf0d9)

### Expected behavior

There should be no warning .

**Comment by aussedatlo** [comment]
Should be fixed since version [6.31.0](https://www.npmjs.com/package/@ledgerhq/hw-transport/v/6.31.0)
