### ISSUE TITLE
[Bug]: Ledger Nano S breaks during ethereum app installation

### ISSUE THREAD

**Issue by netindev** [LedgerHQ/ledger-live#7444]
### Describe the bug

Impacted Library name
No response

Impacted Library version
No response

Describe the bug
Version of ledger live used: v2.84
My ledger nano s literally breaks after Ethereum app installation, it only happens on Windows 10, i wasn't able to reproduce the same issue over Arch Linux.

Installing the bitcoin app first seems to at least work for the bitcoin app.

It's not a cable issue since i used the same.

Detail: my ledger nano s literally broke requiring setup the English words phrase!  

### Expected behavior

Installation of any other app should work

### Additional context

Not reproducible on Arch Linux

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
@netindev 
Regards
