### ISSUE TITLE
[Bug]: buffer is used but not polyfilled

### ISSUE THREAD

**Issue by barthuijgen** [LedgerHQ/ledger-live#7526]
### Impacted Library name

@ledgerhq/hw-transport-webhid

### Impacted Library version

6.29.2

### Describe the bug

Loading the module "@ledgerhq/hw-transport-webhid" into a clean vite project and trying to use it gives the following error:

```
@ledgerhq_hw-transport-webhid.js?v=1f4840ea:2899 Uncaught ReferenceError: Buffer is not defined
    at @ledgerhq_hw-transport-webhid.js?v=1f4840ea:2899:9
(anonymous) @ @ledgerhq_hw-transport-webhid.js?v=1f4840ea:2899
```

### Expected behavior

It should just work.

### Additional context

When you build a library meant to be used in the web, and you use dependencies that are not web-native. Polyfil them yourselves! Why are you passing this burden onto every consumer? Just add the "buffer" dependency, and import it every time you use it instead of acting like it is globally available when you know it is not.

**Comment by salochara** [comment]
Hi 

I am facing the same issue. 
Have you found a workaround?

**Comment by barthuijgen** [comment]
Made my own library as workaround. Wouldn't advise using it though, It's not well tested and my use case isn't for production at this time. https://github.com/barthuijgen/ledger-transport-hid

This issue really should be fixed, no idea how this lib passed any sort of QA.

**Comment by salochara** [comment]
Thanks for sharing it! @barthuijgen 

Yeah, I agree. This should be fixed! 🙏🏼

**Comment by barthuijgen** [comment]
Why is it closed?

**Comment by ledger32570** [comment]
These ledger SDKs are terrible. Such a poor developer experience.
