### ISSUE TITLE
 Connection of wallet-api with non live apps

### ISSUE THREAD

**Issue by gvash** [LedgerHQ/ledger-live#7567]
### Describe your feature request

I see wallet API does provide minimal but good use cases. My question is - Can we send transport extracted from @ledgerhq/react-native-hw-transport-ble and use that to initialise the Wallet-API so I can use the useSignMessage hook?

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
@gvash 
Regards.
