### ISSUE TITLE
[Bug]: silent TransportWebHID failure for Ledger Stax and Flex

### ISSUE THREAD

**Issue by DanielSinclair** [LedgerHQ/ledger-live#7611]
### Impacted Library name

@ledgerhq/hw-transport-webhid

### Impacted Library version

6.29.2

### Describe the bug

When attempting to connect a Stax or Flex device using the SDK, the transport will quietly fail at the transport creation step. User receives the HID request, but the SDK hangs after it is accepted.

Example usage:
```ts
let transport = await TransportWebHID.create();
const appEth = new AppEth(transport);
const result = await appEth.getAddress(
  getHDPathForVendorAndType(0, 'Ledger'),
  false,
  false,
);
```

Console includes the following log when the Chrome HID request appears:
```
Chooser dialog is not displaying a FIDO HID device: vendorId=11415, productId=28693, name='Ledger Flex', serial='0001'
```

### Expected behavior

Successfully pair with Ledger device, or throw an error that the transport pairing has failed.

### Additional context

A reference implementation for Rainbow Wallet is available here: https://github.com/rainbow-me/browser-extension/blob/cf5a7051818905bffa56f5c8ab5bef7040f76f53/src/entries/popup/handlers/wallet.ts#L443

Screenshot of the HID and accompanying logs: 
<img width="1192" alt="Screenshot 2024-08-16 at 1 55 35 AM" src="https://github.com/user-attachments/assets/b21d28f8-748e-4161-84a4-27edb8acd9ca">

**Comment by DanielSinclair** [comment]
cc @KVNLS in case you happen to be the codeowner for transport issues

**Comment by JordaneJL** [comment]
@DanielSinclair our QA and tech team was not able to reproduce, just slacked you so I get gather more information on this issue.

**Comment by JordaneJL** [comment]
Issue has been reported by Rabby too.

**Comment by vvvvvv1vvvvvv** [comment]
I can't help debug or reproduce now since it was fixed by re-pairing the device with Chrome.
Trying to describe what happened on my side:
1. I upgrade Ethereum of my Ledger Stax to version 1.12.1(OS version 1.5.0)
2. trying to sign a transaction on Rabby(paired before), failed(sorry didn't catch error message that time)
3. the same thing happened to my colleague, he found that re-pairing would fix
4.  re-pairing(remove hid permission and re-allow) on my side and issue fixed

**Comment by teebszet** [comment]
Hi, xverse dev here. 

we've had user reports of Ledger Flex and Ledger Stax not being able to connect to the xverse browser extension, and internally we use @ledgerhq/hw-transport-webusb 6.29.4

similarly to this issue, the connection seems to silently fail and hang on [TransportWebUSB.create()](https://github.com/secretkeylabs/xverse-web-extension/blob/bdbd6a008fd3d8f04ea18eca0374fae67d90114c/src/app/screens/ledger/importLedgerAccount/index.tsx#L62)

All of our user reports have been on Windows, Chrome, and for me also, I'm only able to reproduce it on Windows.

Does anyone have any more information on this?

**Comment by kyranjamie** [comment]
Leather team here. Sad to see nothing from Ledger since Feb, this is an on-going issue.

This ultra-simple demo POCs the issue. I can create a transport on macOS but not Windows since firmware 1.4.0.

https://stackblitz.com/edit/vitejs-vite-pvacofhe?file=src%2Fmain.ts
