### ISSUE TITLE
Module not found '@ledgerhq/devices/hid-framing' / https://registry.yarnpkg.com/@ledgerhq%2fdevices/hid-framing returned a 405

### ISSUE THREAD

**Issue by dima-brook** [LedgerHQ/ledger-live#763]
**Details**
- Impacted Library: [e.g. `@ledgerhq/devices`] 
- Version: [e.g. `7.0.0`]

**Describe the bug**

After a clean installation of the latest version 7.0.0 the following error occurs:

Trace: 
  Error: https://registry.yarnpkg.com/@ledgerhq%2fdevices/hid-framing: Request "https://registry.yarnpkg.com/@ledgerhq%2fdevices/hid-framing" returned a 405
      at Request.params.callback [as _callback] (/Users/dimabrook/.yarn/lib/cli.js:67038:18)
      at Request.self.callback (/Users/dimabrook/.yarn/lib/cli.js:140883:22)
      at Request.emit (node:events:390:28)
      at Request.<anonymous> (/Users/dimabrook/.yarn/lib/cli.js:141855:10)
      at Request.emit (node:events:390:28)
      at IncomingMessage.<anonymous> (/Users/dimabrook/.yarn/lib/cli.js:141777:12)
      at Object.onceWrapper (node:events:509:28)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Expected behavior**

Should compile and build.

**Additional context**

Trying to run:

```
$ yarn add @ledgerhq/devices/hid-framing
```

Returns this error:

error An unexpected error occurred: "https://registry.yarnpkg.com/@ledgerhq%2fdevices/hid-framing: Request \"https://registry.yarnpkg.com/@ledgerhq%2fdevices/hid-framing\" returned a 405".

**Comment by gre** [comment]
@dima-brook 
`yarn add @ledgerhq/devices` should be the way to install that library, not `yarn add @ledgerhq/devices/hid-framing`

**Comment by dima-brook** [comment]
<img width="1188" alt="Screen Shot 2022-07-28 at 17 41 37" src="https://user-images.githubusercontent.com/81907112/181563242-d4b4520f-ef19-4921-8af8-146d868102cc.png">

We've already found the issue. It is here:

**Comment by elbywan** [comment]
Hey @dima-brook @gre 👋,

> We've already found the issue. 

I don't think this is a problem, @ledgerhq/devices relies on package exports which should map `@ledgerhq/devices/hid-framing` to `@ledgerhq/devices/lib/hid-framing` or `@ledgerhq/devices/lib-es/hid-framing` depending on the bundler configuration.

I tried to reproduce by creating a new app using `create-react-app` (since you are using `react-app-rewired`) and I managed to `yarn build` without issues.

I did both:

```sh
yarn add @ledgerhq/hw-transport-webhid
```

```js
import TransportWebHID from "@ledgerhq/hw-transport-webhid";
```

 and:

```sh
yarn add @ledgerhq/devices
```

```js
import hidFraming from "@ledgerhq/devices/hid-framing";
```

My guess is that your stack relies on webpack 4 which does not support [subpath exports](https://nodejs.org/api/packages.html#subpath-exports).

In any case I don't see any issues with the library itself.

**Comment by oleg-savenok** [comment]
You can use NormalModuleReplacementPlugin if you stuck with webpack 4.

```
plugins: [
	new webpack.NormalModuleReplacementPlugin(
		/@ledgerhq\/devices\/hid-framing/,
		'@ledgerhq/devices/lib/hid-framing'
	)
],
```

**Comment by jordansexton** [comment]
FWIW `@ledgerhq/hw-transport` and `@ledgerhq/hw-transport-webhid` work when pinned to the previous exact version `6.27.1` (published 2022-04-13), and this error is encountered with the latest release (`6.27.2`, published ~ a week ago, 2022-07-28).

**Comment by alihalabyah** [comment]
@jordansexton Tried that but it did not work

**Comment by jordansexton** [comment]
@alihalabyah pinning versions is tricky because the dependencies declare their transitive deps with `^`.

Check out how we do this with exact versions and yarn resolutions here: https://github.com/solana-labs/wallet-adapter/commit/88f3576894702d8978172ad5673cd17a53148e68

This forces the resolved transitive deps to be pinned as well.

**Comment by jordansexton** [comment]
You'll know you did it right if you check your yarn.lock file and see only 6.27.1: https://github.com/solana-labs/wallet-adapter/blob/5437f957740e8651467b9eb74bf1d7ef77817f8f/yarn.lock#L1906-L1938

**Comment by elbywan** [comment]
#### So to sum it up.

Following this PR https://github.com/LedgerHQ/ledger-live/pull/364 `@ledgerhq/device` is now transpiled to commonjs and esm (in the `/lib` and `/lib-es` folders respectively).

Subpath exports have thus been added to use the same path (without /lib and /lib-es) in imports and allow consuming bundlers to declare which flavour of the dependency they want.

✅  For users of `webpack@5`, `esbuild` or other bundlers that support [subpath exports](https://nodejs.org/api/packages.html#subpath-exports) everything should be working fine.

⚠️ For users of other bundlers (`parcel` for instance - or `webpack@4`):
- upgrade your bundler
- configure your bundler to map `@ledgerhq/devices` to `@ledgerhq/devices/lib-es` (or `@ledgerhq/devices/lib`, depending if you want the commonjs or esm flavour).
- use another bundler

_With `webpack@4` adding the following line to the config should make it work:_

```js
resolve: {
  alias: {
    "@ledgerhq/devices": "@ledgerhq/devices/lib-es",
  },
},
```

**Bottom line, I do not see anything wrong in the library from what has been posted so far.**

Users stuck with `webpack@4` can add a single configuration line to map to the right path, and other users should upgrade anyway (there are only a few breaking changes between v4 and v5 - released 2 years ago).

-----

**The following demonstrate that the lib works fine with a compatible bundler.**

- `npx create-react-app hw-transport-webhid-test`
- `cd hw-transport-webhid-test`
- `npm i @ledgerhq/hw-transport-webhid buffer`
- Add the following code:

```js
// src/App.js
import TransportWebHID from "@ledgerhq/hw-transport-webhid";
console.log(TransportWebHID);

// src/polyfill.js
import { Buffer } from "buffer";
window.Buffer = Buffer;

// src/index.js
import "./polyfill";
```
- `npm start`

Builds and prints:

<img width="407" alt="Screenshot 2022-08-09 at 12 20 20" src="https://user-images.githubusercontent.com/3428394/183625149-62d99e2c-3589-4e35-8d65-49555d71e3b7.png">

**Comment by AlexeyAdoniev** [comment]
Quick workaround:

1. package.json

```
"dependencies": {
    "react-app-rewired": "^2.2.1",
  },

 "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
  },
  
```
  
 2. config-overrides.js in root

```
module.exports = function override(webpackConfig) {
     
 webpackConfig.resolve.alias = {
    ...webpackConfig.resolve.alias,
    "@ledgerhq/devices/hid-framing": "@ledgerhq/devices/lib/hid-framing",
  };


}
```

**Comment by ihorbond** [comment]
Sounds like this should have been a breaking change, not just a minor patch.

**Comment by elbywan** [comment]
> Sounds like this should have been a breaking change, not just a minor patch.

Yes, this is an oversight. `@ledgerhq/devices` got a major bump but not the consuming packages.

**Comment by nebolsin** [comment]
Just want to point out the official [Connecting an app](https://developers.ledger.com/docs/transport/web-hid-usb/) tutorial uses `parcel` and is also broken now.

Adding parcel-style alias to the `package.json` seems to help:

```package.json
{ 
  ...
  "alias": {
    "@ledgerhq/devices": "@ledgerhq/devices/lib-es"
  }
}
```

**Comment by elbywan** [comment]
@nebolsin Thanks, good catch 🙇 ! The tutorial needs to be updated.

@cfranceschi-ledger Sorry for the wild ping but I think you worked on it based on the [file history](https://github.com/LedgerHQ/developer-portal/blob/main/_docs/transport/web-hid-usb.md).

**Comment by AmmarKhalid123** [comment]
Just a little correction in step 2:

> 2. config-overrides.js in root
> 
> ```
> module.exports = function override(webpackConfig) {
>      
>  webpackConfig.resolve.alias = {
>     ...webpackConfig.resolve.alias,
>     "@ledgerhq/devices/hid-framing": "@ledgerhq/devices/lib/hid-framing",
>   };
> 
>  return webpackConfig;
> }
> ```

**Comment by landabaso** [comment]
This also broke the metro bundler for react-native.

If anyone gets that problem, you need to update babel.config.js to:
```javascript
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['.'],
        alias: {
          '@ledgerhq/devices/hid-framing': '@ledgerhq/devices/lib/hid-framing',
        },
      },
    ],
  ],
};
```
Remember then to reset the cache before bulding it again: `npm start -- --reset-cache`

**Comment by hbriese** [comment]
> This also broke the metro bundler for react-native which does not support subpath exports (yet).
> 
> If anyone gets that problem, you need to update babel.config.js to:
> 
> ```js
> module.exports = {
>   presets: ['module:metro-react-native-babel-preset'],
>   plugins: [
>     [
>       'module-resolver',
>       {
>         root: ['.'],
>         alias: {
>           '@ledgerhq/devices/hid-framing': '@ledgerhq/devices/lib/hid-framing',
>         },
>       },
>     ],
>   ],
> };
> ```
> 
> Remember then to reset the cache before bulding it again: `npm start -- --reset-cache`
> 
> Related: [facebook/metro#670](https://github.com/facebook/metro/issues/670)

As of react native 0.72 (expo 49) metro now supports package exports
The (beta) feature needs to be [enabled in your metro config](https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks#enabling-beta-features)
