### ISSUE TITLE
Can't install ledger-live

### ISSUE THREAD

**Issue by Sebybear** [LedgerHQ/ledger-live#769]
Hello,
When I execute yay -S ledger-live : 

 apps/ledger-live-desktop postinstall$ node ./scripts/post-install.js
│ running
│ no previous checksum saved, will rebuild native deps and save new checksum
│ node:internal/errors:477
│     ErrorCaptureStackTrace(err);
│     ^
│ Error: spawn npm ENOENT
│     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
│     at onErrorNT (node:internal/child_process:476:16)
│     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
│   errno: -2,
│   code: 'ENOENT',
│   syscall: 'spawn npm',
│   path: 'npm',
│   spawnargs: [ 'run', 'install-deps' ]
│ }
│ Node.js v18.7.0
└─ Failed in 124ms
 ELIFECYCLE  Command failed with exit code 1.
==> ERROR: A failure occurred in build().
Aborting...
-> error making: ledger-live

Archlinux x64
kernel 5.18.12-arch1-1
**Smartphone (please complete the following information):**

**Comment by gre** [comment]
Hey, thanks for this ticket.
Unfortunately we don't officially maintain the AUR package and don't officially support ArchLinux yet, at the moment Ledger Live is only provided as a AppImage.
