### ISSUE TITLE
Unable to resolve module in react-native-hw-transport-ble

### ISSUE THREAD

**Issue by wolverineks** [LedgerHQ/ledger-live#777]
**Details**
@ledgerhq/react-native-hw-transport-ble
"6.27.2"

pixel 6

**Describe the bug**

```
Error: Unable to resolve module @ledgerhq/devices/ble/sendAPDU from @ledgerhq/react-native-hw-transport-ble/lib/BleTransport.js: @ledgerhq/devices/ble/sendAPDU could not be found within the project or in these directories:
  node_modules/@ledgerhq/react-native-hw-transport-ble/node_modules
  node_modules
```

**Actual behavior**
fails to compile

**Expected behavior**
_A clear and concise description of what you expected to happen._
compiles

**Comment by elbywan** [comment]
Hey @wolverineks 👋,

This module now relies on [subpath exports](https://nodejs.org/api/packages.html#subpath-exports), you did not provide enough information about your stack but you should use a bundle that supports package exports (typically webpack 5+).

Please check the latest changelog, expecially the [breaking changes](https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledgerjs/packages/hw-transport-web-ble/CHANGELOG.md#ledgerhqhw-transport-web-ble) part.

**Comment by wolverineks** [comment]
yikes, looks like metro doesnt like this either
`Error: EISDIR: illegal operation on a directory, read`
https://github.com/facebook/metro/issues/658

also the link to the node issue in the release notes is broken

**Comment by elbywan** [comment]
Weird, I tried the following steps and it seems fine on my end with latest react-native (0.69):

- Create a new app:

```sh
npx react-native init TestLedgerProjectBare
cd TestLedgerProjectBare/
yarn add @ledgerhq/hw-transport-webhid
```

- Install [react-native-ble-plx](https://github.com/dotintent/react-native-ble-plx)

- Add the snippet  I pasted to the `metro.config.js` file 

-  Add the following code in the `App.js` file:

```js
import TransportBLE from "@ledgerhq/react-native-hw-transport-ble";

console.log(TransportBLE)
```

- Run the app:

```sh
yarn start
yarn ios
```

- Logs:

```sh
 LOG  [Function BluetoothTransport]
 LOG  Running "TestLedgerProjectBare" with {"rootTag":11,"initialProps":{}}
```

---- 

Maybe your version of react-native is older and uses an outdated version of metro wich has a different signature for the `resolveRequest` function.

You could try to change the snippet with:

```js
resolveRequest: (context, realModuleName, platform, moduleName) => {
    if (moduleName.startsWith('@ledgerhq/devices')) {
      return {
        filePath: require.resolve(moduleName, {
          paths: [
            require('path').dirname(context.originModulePath),
          ],
        }),
        type: 'sourceFile',
      };
    }

    delete context.resolveRequest;

    return context.resolveRequest(context, realModuleName, platform, moduleName);
  }
```

**Comment by ThalesBMC** [comment]
@elbywan  Any news about this issue? I'm having the same problem.

**Comment by Perronef5** [comment]
Shouldn't have this been a breaking change?

**Comment by ThalesBMC** [comment]
Just downgrade the version and you should be fine.

**Comment by Perronef5** [comment]
Yeah we did that already. Still doesn't answer the question.

**Comment by billyjacoby** [comment]
I had this same error and just ended up patching the package with the following .patch file:

```
diff --git a/node_modules/@ledgerhq/react-native-hw-transport-ble/lib/BleTransport.js b/node_modules/@ledgerhq/react-native-hw-transport-ble/lib/BleTransport.js
index 1144799..1ed6531 100644
--- a/node_modules/@ledgerhq/react-native-hw-transport-ble/lib/BleTransport.js
+++ b/node_modules/@ledgerhq/react-native-hw-transport-ble/lib/BleTransport.js
@@ -86,8 +86,8 @@ exports.setReconnectionConfig = void 0;
 var hw_transport_1 = __importDefault(require("@ledgerhq/hw-transport"));
 var react_native_ble_plx_1 = require("react-native-ble-plx");
 var devices_1 = require("@ledgerhq/devices");
-var sendAPDU_1 = require("@ledgerhq/devices/ble/sendAPDU");
-var receiveAPDU_1 = require("@ledgerhq/devices/ble/receiveAPDU");
+var sendAPDU_1 = require("@ledgerhq/devices/lib/ble/sendAPDU");
+var receiveAPDU_1 = require("@ledgerhq/devices/lib/ble/receiveAPDU");
 var logs_1 = require("@ledgerhq/logs");
 var rxjs_1 = require("rxjs");
 var operators_1 = require("rxjs/operators");

```

**Comment by elbywan** [comment]
> Shouldn't this have been a breaking change?

This is an oversight, `@ledgerhq/devices` did get a major bump but it was not foreseen that react-native consumers would suffer from this.

#879 should fix this, and will get included in the next release.
