### ISSUE TITLE
Ledger lives signatures

### ISSUE THREAD

**Issue by Daniel-Kelvich** [LedgerHQ/ledger-live#778]
Why can't you spend 5 minutes and add ledger live signatures to your website? This behavior is very concerning for a security company. Just got my ledger and planning to return it back because of the lack of transparency.

**Comment by tjanez** [comment]
Just noting that Ledger recognized the issue at:
https://support.ledger.com/hc/en-us/articles/4404807946001-How-to-verify-the-authenticity-of-Ledger-Live-?support=true

![Screenshot from 2022-07-29 12-57-07](https://user-images.githubusercontent.com/2518544/181745299-22177712-8122-49a6-a960-a0803e80c983.png)

However, it is outdated in the sense that Ledger Live Desktop 2.45.0 has been released and still has not signatures available.

Also, the site linked below only works up until Ledger Live Desktop 2.42.0:
https://www.ledger.com/ledger-live/lld-signatures

![Screenshot from 2022-07-29 13-00-29](https://user-images.githubusercontent.com/2518544/181745776-82189213-7f82-4c35-bfd6-3d59ca074dc8.png)

**Comment by Al-cm** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/67399090/181809162-41129a40-a113-4ebf-9c31-9f0c6026b089.png">

When clicking the link, I get the signature for the current version. Maybe this issue can be closed?
