### ISSUE TITLE
[Bug]: Android 14 usb support

### ISSUE THREAD

**Issue by jorbuedo** [LedgerHQ/ledger-live#7786]
### Impacted Library name

@ledgerhq/react-native-hid

### Impacted Library version

all

### Describe the bug

After upgrading Android project to sdk 34 (which is now required to publish to play store), the following error occurs:
```
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
```

### Expected behavior

App should not crash when using the library.

### Additional context

https://stackoverflow.com/a/77276774

Lines:
https://github.com/LedgerHQ/ledger-live/blob/8649ebf286d15c2cd97426ae03009d4ef2d28f4e/libs/ledgerjs/packages/react-native-hid/android/src/main/java/com/ledgerwallet/hid/ReactHIDModule.java#L61

and 
https://github.com/LedgerHQ/ledger-live/blob/8649ebf286d15c2cd97426ae03009d4ef2d28f4e/libs/ledgerjs/packages/react-native-hid/android/src/main/java/com/ledgerwallet/hid/ReactHIDModule.java#L216

Need to be updated to include RECEIVER_NOT_EXPORTED like
```
getReactApplicationContext().registerReceiver(receiver, intFilter, RECEIVER_NOT_EXPORTED); 
```

Or rather this for retrocompatibility
```
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            getReactApplicationContext().registerReceiver(receiver, intFilter, Context.RECEIVER_NOT_EXPORTED);
        } else {
            getReactApplicationContext().registerReceiver(receiver, intFilter);
        }
```

**Comment by nicolas-meilan** [comment]
I create this PR that fix the error: https://github.com/LedgerHQ/ledger-live/pull/7880

**Comment by jorbuedo** [comment]
Still an issue, the PR is just stuck it seems.

**Comment by SasmitaNovitasari** [comment]
why this error not fixed in the latest update ?

**Comment by jorbuedo** [comment]
That's a good question.
