### ISSUE TITLE
[Bug]: `TypeError: this.listen is not a function` Get this error when i am creating the transport!

### ISSUE THREAD

**Issue by SukiratWarring** [LedgerHQ/ledger-live#7889]
### Impacted Library name

@ledgerhq/hw-transport

### Impacted Library version

"^6.31.3"

### Describe the bug

`TypeError: this.listen is not a function` Get this error when i am creating the transport!
Code
```
import Transport from "@ledgerhq/hw-transport";
const sui = new Sui(await Transport.create());
```

### Expected behavior

It should execute succesfully and create the transport instance

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@SukiratWarring 
Support.
  {c}2024
