### ISSUE TITLE
Can't find @ledgerhq/devices/hid-framing 

### ISSUE THREAD

**Issue by oleg-savenok** [LedgerHQ/ledger-live#799]
https://github.com/LedgerHQ/ledger-live/blob/ae290e27c6bcc0fc224762836eb49bfb7f3aed18/libs/ledgerjs/packages/hw-transport-webhid/src/TransportWebHID.ts#L7

Can be fixed with replacing `import hidFraming from "@ledgerhq/devices/hid-framing";` with `import hidFraming from "@ledgerhq/devices/lib/hid-framing";`

**Comment by elbywan** [comment]
Duplicate of #763
