### ISSUE TITLE
Allow assets to be (temporarily) excluded from history chart on Portfolio screen

### ISSUE THREAD

**Issue by samsta** [LedgerHQ/ledger-live#807]
**Context**

Ledger Live Portfolio screen, history chart.

**Is your feature request related to a problem? Please describe.**

DOT transactions don't show up on Ledger Live, apparently because there's no batch transaction support yet.
While the DOT balance is right, Ledger Live makes it appear as though the entire balance was received on the current day,
causing an upspike on the history chart of the total balance on the current day. This skews the visual representation quite a bit.

**Describe the solution you'd like**

Ideally, of course, I'd like to see DOT fully supported, but this feature request isn't about that.

I'd like to be able to (temporarily) exclude assets from the total balance history chart as this would mitigate the presentation issue.

**Describe alternatives you've considered**

My alternative so far is to delete the DOT account temporarily and add it again, but that's a bit time consuming and awkward.

**Additional context**

![Total Balance History Chart](https://user-images.githubusercontent.com/3915450/182346761-56517856-3713-41b7-8152-cb5fcaea4f9d.png)

As you can see, it looks like my portfolio went up at the very end, when in fact it went down. What makes it appear to go up is simply the fact that the DOT that I bought several days ago got lumped into the current day

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

Could you please contact our tech support with your problem so they can investigate more deeply what kind of transaction is problematic here?

https://support.ledger.com/

I don't think we consider a workaround feature to hide balance history calculation from graph but instead we will prefer to fix the problem.

Best,
gre
