### ISSUE TITLE
ARM64 build for Windows

### ISSUE THREAD

**Issue by matze19999** [LedgerHQ/ledger-live#809]
There are so many new devices out there with Windows for ARM on board, but we can only use ledger live in emulation mode, which makes it extremly slow and almost not possible to use.

Can we please get an ARM64 build for Windows?

**Comment by gotgot1995** [comment]
Also, it would be great to have an ARM64 build for Linux devices (RaspberryPi, Pinephone, Librem 5).

**Comment by lacamar** [comment]
Given that Asahi linux (ARM64 Linux on Apple ARM silicon) is now being used by Linus Torvalds himself to develop the Linux kernel, ARM64 Linux can no longer be disregarded as a hobbyist platform. It will continue to increase in significance for end users and developers, so professional projects such as Ledger Live really ought to release ARM64 builds.

**Comment by valpinkman** [comment]
Thank you for raising this issue. We will definitely have a look at it whenever we have the time. I will keep you posted.

@gotgot1995 not sure we will ever support RaspberryPi and such other linux distribution, not in our radar for now

**Comment by gotgot1995** [comment]
@valpinkman RaspberryPi OS was just an example. But if any ARM64 build is ever done, it should run on pretty much anything.

**Comment by valpinkman** [comment]
Hello guys. 

So we come back with not that great news. Building for arm on windows and linux is very tricky for us today. 
It technically challenging with the stack we have. It is not prioritized, and we have no ways to actually test nor the bandwidth. 

This is unfortunate for now, but it cannot be prioritised. If we have more users that are actually on those platform, maybe it could be. 

But for now we won't be able to provide you with a build for your architectures.

**Comment by gre** [comment]
Hi and sorry for the delay in answering on this Github issue.
We now only use Github issues for developers topics (typically on topics that concerns our SDK, libraries,..). For questions, feature requests or Ledger Live issues, please also go through our Customer Support to raise this voice and have it more prioritised: https://support.ledger.com/

Thanks
