### ISSUE TITLE
[Bug]: CSV export: broken account names

### ISSUE THREAD

**Issue by GittyGitGitGitty** [LedgerHQ/ledger-live#8101]
### Impacted Library name

@ledgerhq/ledger-live-common

### Describe the bug

Appears to be introduced in https://github.com/LedgerHQ/ledger-live/pull/7813

1. CSV column 'Account Name' no longer exports correct account names. Account names such as "MyCustomWalletName" are now exported as "Bitcoin 1" or similar.

2. Additionally, multiple wallets of the same chain appear to not increment beyond 2. For example: 3 different Bitcoin wallets appear to be given the account names "Bitcoin 1", "Bitcoin 2", "Bitcoin 2" in the exported CSV.

### Expected behavior

As in previous ledger-live versions, account names should be exported as given. If an account is named "MyCustomWalletName", the 'Account Name' column should export "MyCustomWalletName".

**Comment by LucasWerey** [comment]
Hello @GittyGitGitGitty could you provide the app version you are using please ? I can't reproduce this with latest build

**Comment by GittyGitGitGitty** [comment]
2.89.1
https://aur.archlinux.org/packages/ledger-live
