### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Retropex** [LedgerHQ/ledger-live#826]
I don't know what to do for this error can someone help me ?
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/74937347/182652279-fdd93a20-5952-4a2b-87e3-fda66a5cd559.png">

**Comment by elbywan** [comment]
Hey @Retropex, I'm sorry but there is not enough information to provide any specific help.

Please make sure you followed closely the [React Native guide](https://reactnative.dev/docs/environment-setup) and properly installed all the [Live Mobile requirements](https://github.com/LedgerHQ/ledger-live/tree/develop/apps/ledger-live-mobile#pre-requisites).
