### ISSUE TITLE
[Feature]: support stellar via walletconnect

### ISSUE THREAD

**Issue by tomerweller** [LedgerHQ/ledger-live#8280]
### Describe your feature request

Walletconnect does not work with Stellar dapps even though Stellar is supported on ledger live and the walletconnect protocol. 

![image](https://github.com/user-attachments/assets/b5aebf54-1ad5-4aa9-b048-cd86d705ea61)

**Comment by Elsiehwoods** [comment]
@tomerweller It sounds like you're running into compatibility issues.I'll have to refer you to the official support live chat with the ticket ID LED07638
Please see the link below to our dedicated support line:
[ledger Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Jamesoliver000** [comment]
> ### Library name
> _No response_
> 
> ### Describe your feature request
> Walletconnect does not work with Stellar dapps even though Stellar is supported on ledger live and the walletconnect protocol.
> 
> ![image](https://private-user-images.githubusercontent.com/815704/382514702-b5aebf54-1ad5-4aa9-b048-cd86d705ea61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjczMjAsIm5iZiI6MTczMDYyNzAyMCwicGF0aCI6Ii84MTU3MDQvMzgyNTE0NzAyLWI1YWViZjU0LTFhZDUtNGFhOS1iMDQ4LWNkODZkNzA1ZWE2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwOTQzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGRjODQ5OTYxZDk1ZjQyMDdmMGUwZDZmMDk0MGEzOTQ1ODNhNzhiYmZhZTRiMDA2M2M2MTI4MzZhZGZlZTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cak7i_Y7nFEKF3Y-pA8qJHaiYa-EbHCfXq6u_lqzr2U)


Hey @tomerweller Yeah, that can be frustrating! Even though Stellar is supported on Ledger Live and the WalletConnect protocol, some dApps might not have full integration yet. It could be a compatibility issue or something specific to the dApp itself. If you’re having consistent issues, it might help to check if there are any updates from the developers or see if there’s a workaround suggested in their community forums.
