### ISSUE TITLE
[Bug]: Type 'EventEmitter' is not generic

### ISSUE THREAD

**Issue by teacoat** [LedgerHQ/ledger-live#8553]
### Impacted Library name

@ledgerhq/hw-transport, @ledgerhq/hw-transport-webhid, @ledgerhq/hw-transport-web-ble

### Impacted Library version

6.31.4, 6.29.4

### Describe the bug

```
Error: node_modules/@ledgerhq/hw-transport/lib/Transport.d.ts:135:14 - error TS2315: Type 'EventEmitter' is not generic.

135     _events: EventEmitter<[never]>;
```

### Expected behavior

No errors

**Comment by zhangpeng11** [comment]
hi, do you know how to resolve this issue?
