### ISSUE TITLE
SYN (ERC20) incorrect address

### ISSUE THREAD

**Issue by BlazeWasHere** [LedgerHQ/ledger-live#931]
**Details**
@ledgerhq/cryptoassets

**Describe the bug**

Incorrect token address is used in `data/erc20.js`
```
["ethereum","synapse","SYN",18,"Synapse","304402205c40c4050a517fe73072153eb81ef76129b5c62df12ebaa3ceba6a5b185fc585022047891f151213c41bfd88d7dad808a274f8f2c8b2df7568614d0bfd1c79f82c6d","0x10B123FdDde003243199aaD03522065dC05827A0",true,true],
```

**Expected behavior**

Address change of `0x10B123FdDde003243199aaD03522065dC05827A0` to `0x0f2D719407FdBeFF09D87557AbB7232601FD9F29`

**Additional context**

When looking at etherscan, compare the [incorrect SYN](https://etherscan.io/token/0x10B123FdDde003243199aaD03522065dC05827A0) to the [correct SYN](https://etherscan.io/token/0x0f2d719407fdbeff09d87557abb7232601fd9f29). There is a huge difference in both users and transactions.

And the correct SYN address can be verified on "Contract" on [coingecko](https://www.coingecko.com/en/coins/synapse) as well as their official docs [here](https://docs.synapseprotocol.com/reference/contract-addresses#synapse-token)

Incorrect token:
![image](https://user-images.githubusercontent.com/69124640/184630361-654ec526-b2ed-402d-aeb0-b1a8ce67dc35.png)

Correct token:
![image](https://user-images.githubusercontent.com/69124640/184630375-eebe747a-fd7d-4357-a380-9dfcbabff8e7.png)

**Comment by adrienlacombe-ledger** [comment]
hi @BlazeWasHere there is no such thing as correct or incorrect token, what issue do you see in Ledger Live please?

**Comment by gre** [comment]
Hi and sorry for the delay in answering on this Github issue.
We now only use Github issues for developers topics (typically on topics that concerns our SDK, libraries,..). For questions, feature requests or Ledger Live issues, please go through our Customer Support to raise this voice and have it more prioritised: https://support.ledger.com/

Thanks
